[2024-03-09T00:58:47.257+0000] {processor.py:161} INFO - Started process (PID=43) to work on /opt/airflow/dags/dag1.py
[2024-03-09T00:58:47.258+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag1.py for tasks to queue
[2024-03-09T00:58:47.259+0000] {logging_mixin.py:188} INFO - [2024-03-09T00:58:47.259+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/dag1.py
[2024-03-09T00:58:47.262+0000] {logging_mixin.py:188} INFO - [2024-03-09T00:58:47.262+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/dag1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag1.py", line 2, in <module>
    from airflow.operators import PythonOperator
ImportError: cannot import name 'PythonOperator' from 'airflow.operators' (/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/__init__.py)
[2024-03-09T00:58:47.263+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag1.py
[2024-03-09T00:58:47.281+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag1.py took 0.027 seconds
[2024-03-09T00:59:17.731+0000] {processor.py:161} INFO - Started process (PID=100) to work on /opt/airflow/dags/dag1.py
[2024-03-09T00:59:17.733+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag1.py for tasks to queue
[2024-03-09T00:59:17.734+0000] {logging_mixin.py:188} INFO - [2024-03-09T00:59:17.734+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/dag1.py
[2024-03-09T00:59:17.736+0000] {logging_mixin.py:188} INFO - [2024-03-09T00:59:17.736+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/dag1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag1.py", line 2, in <module>
    from airflow.operators import PythonOperator
ImportError: cannot import name 'PythonOperator' from 'airflow.operators' (/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/__init__.py)
[2024-03-09T00:59:17.737+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag1.py
[2024-03-09T00:59:17.755+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag1.py took 0.027 seconds
[2024-03-09T00:59:48.154+0000] {processor.py:161} INFO - Started process (PID=157) to work on /opt/airflow/dags/dag1.py
[2024-03-09T00:59:48.155+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag1.py for tasks to queue
[2024-03-09T00:59:48.157+0000] {logging_mixin.py:188} INFO - [2024-03-09T00:59:48.156+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/dag1.py
[2024-03-09T00:59:48.159+0000] {logging_mixin.py:188} INFO - [2024-03-09T00:59:48.158+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/dag1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag1.py", line 2, in <module>
    from airflow.operators import PythonOperator
ImportError: cannot import name 'PythonOperator' from 'airflow.operators' (/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/__init__.py)
[2024-03-09T00:59:48.159+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag1.py
[2024-03-09T00:59:48.172+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag1.py took 0.022 seconds
[2024-03-09T01:00:18.749+0000] {processor.py:161} INFO - Started process (PID=214) to work on /opt/airflow/dags/dag1.py
[2024-03-09T01:00:18.752+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag1.py for tasks to queue
[2024-03-09T01:00:18.753+0000] {logging_mixin.py:188} INFO - [2024-03-09T01:00:18.753+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/dag1.py
[2024-03-09T01:00:18.755+0000] {logging_mixin.py:188} INFO - [2024-03-09T01:00:18.754+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/dag1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag1.py", line 2, in <module>
    from airflow.operators import PythonOperator
ImportError: cannot import name 'PythonOperator' from 'airflow.operators' (/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/__init__.py)
[2024-03-09T01:00:18.755+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag1.py
[2024-03-09T01:00:18.768+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag1.py took 0.021 seconds
[2024-03-09T01:00:49.533+0000] {processor.py:161} INFO - Started process (PID=271) to work on /opt/airflow/dags/dag1.py
[2024-03-09T01:00:49.535+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag1.py for tasks to queue
[2024-03-09T01:00:49.536+0000] {logging_mixin.py:188} INFO - [2024-03-09T01:00:49.536+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/dag1.py
[2024-03-09T01:00:49.539+0000] {logging_mixin.py:188} INFO - [2024-03-09T01:00:49.538+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/dag1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag1.py", line 2, in <module>
    from airflow.operators import PythonOperator
ImportError: cannot import name 'PythonOperator' from 'airflow.operators' (/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/__init__.py)
[2024-03-09T01:00:49.539+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag1.py
[2024-03-09T01:00:49.556+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag1.py took 0.026 seconds
[2024-03-09T01:01:20.041+0000] {processor.py:161} INFO - Started process (PID=328) to work on /opt/airflow/dags/dag1.py
[2024-03-09T01:01:20.044+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag1.py for tasks to queue
[2024-03-09T01:01:20.045+0000] {logging_mixin.py:188} INFO - [2024-03-09T01:01:20.045+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/dag1.py
[2024-03-09T01:01:20.047+0000] {logging_mixin.py:188} INFO - [2024-03-09T01:01:20.047+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/dag1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag1.py", line 2, in <module>
    from airflow.operators import PythonOperator
ImportError: cannot import name 'PythonOperator' from 'airflow.operators' (/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/__init__.py)
[2024-03-09T01:01:20.047+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag1.py
[2024-03-09T01:01:20.059+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag1.py took 0.021 seconds
[2024-03-09T01:01:25.645+0000] {processor.py:161} INFO - Started process (PID=378) to work on /opt/airflow/dags/dag1.py
[2024-03-09T01:01:25.656+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag1.py for tasks to queue
[2024-03-09T01:01:25.660+0000] {logging_mixin.py:188} INFO - [2024-03-09T01:01:25.659+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/dag1.py
[2024-03-09T01:01:25.742+0000] {logging_mixin.py:188} INFO - [2024-03-09T01:01:25.741+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/dag1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag1.py", line 4, in <module>
    from scrape_hocky import scrape_hockey_data, save_to_csv as save_hockey_to_csv
  File "/opt/airflow/dags/scrape_hocky.py", line 4, in <module>
    import pymongo
ModuleNotFoundError: No module named 'pymongo'
[2024-03-09T01:01:25.742+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag1.py
[2024-03-09T01:01:25.752+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag1.py took 0.116 seconds
[2024-03-09T01:01:56.312+0000] {processor.py:161} INFO - Started process (PID=435) to work on /opt/airflow/dags/dag1.py
[2024-03-09T01:01:56.321+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag1.py for tasks to queue
[2024-03-09T01:01:56.324+0000] {logging_mixin.py:188} INFO - [2024-03-09T01:01:56.323+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/dag1.py
[2024-03-09T01:01:56.372+0000] {logging_mixin.py:188} INFO - [2024-03-09T01:01:56.372+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/dag1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag1.py", line 4, in <module>
    from scrape_hocky import scrape_hockey_data, save_to_csv as save_hockey_to_csv
  File "/opt/airflow/dags/scrape_hocky.py", line 4, in <module>
    import pymongo
ModuleNotFoundError: No module named 'pymongo'
[2024-03-09T01:01:56.372+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag1.py
[2024-03-09T01:01:56.383+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag1.py took 0.076 seconds
[2024-03-09T01:02:26.816+0000] {processor.py:161} INFO - Started process (PID=492) to work on /opt/airflow/dags/dag1.py
[2024-03-09T01:02:26.825+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag1.py for tasks to queue
[2024-03-09T01:02:26.829+0000] {logging_mixin.py:188} INFO - [2024-03-09T01:02:26.828+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/dag1.py
[2024-03-09T01:02:26.875+0000] {logging_mixin.py:188} INFO - [2024-03-09T01:02:26.874+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/dag1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag1.py", line 4, in <module>
    from scrape_hocky import scrape_hockey_data, save_to_csv as save_hockey_to_csv
  File "/opt/airflow/dags/scrape_hocky.py", line 4, in <module>
    import pymongo
ModuleNotFoundError: No module named 'pymongo'
[2024-03-09T01:02:26.875+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag1.py
[2024-03-09T01:02:26.885+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag1.py took 0.074 seconds
[2024-03-09T01:02:57.542+0000] {processor.py:161} INFO - Started process (PID=549) to work on /opt/airflow/dags/dag1.py
[2024-03-09T01:02:57.551+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag1.py for tasks to queue
[2024-03-09T01:02:57.554+0000] {logging_mixin.py:188} INFO - [2024-03-09T01:02:57.554+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/dag1.py
[2024-03-09T01:02:57.602+0000] {logging_mixin.py:188} INFO - [2024-03-09T01:02:57.601+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/dag1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag1.py", line 4, in <module>
    from scrape_hocky import scrape_hockey_data, save_to_csv as save_hockey_to_csv
  File "/opt/airflow/dags/scrape_hocky.py", line 4, in <module>
    import pymongo
ModuleNotFoundError: No module named 'pymongo'
[2024-03-09T01:02:57.602+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag1.py
[2024-03-09T01:02:57.615+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag1.py took 0.076 seconds
[2024-03-09T01:03:28.176+0000] {processor.py:161} INFO - Started process (PID=606) to work on /opt/airflow/dags/dag1.py
[2024-03-09T01:03:28.185+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag1.py for tasks to queue
[2024-03-09T01:03:28.186+0000] {logging_mixin.py:188} INFO - [2024-03-09T01:03:28.186+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/dag1.py
[2024-03-09T01:03:28.223+0000] {logging_mixin.py:188} INFO - [2024-03-09T01:03:28.223+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/dag1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag1.py", line 4, in <module>
    from scrape_hocky import scrape_hockey_data, save_to_csv as save_hockey_to_csv
  File "/opt/airflow/dags/scrape_hocky.py", line 4, in <module>
    import pymongo
ModuleNotFoundError: No module named 'pymongo'
[2024-03-09T01:03:28.223+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag1.py
[2024-03-09T01:03:28.239+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag1.py took 0.067 seconds
[2024-03-09T01:03:58.971+0000] {processor.py:161} INFO - Started process (PID=663) to work on /opt/airflow/dags/dag1.py
[2024-03-09T01:03:58.979+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag1.py for tasks to queue
[2024-03-09T01:03:58.980+0000] {logging_mixin.py:188} INFO - [2024-03-09T01:03:58.980+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/dag1.py
[2024-03-09T01:03:59.017+0000] {logging_mixin.py:188} INFO - [2024-03-09T01:03:59.016+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/dag1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag1.py", line 4, in <module>
    from scrape_hocky import scrape_hockey_data, save_to_csv as save_hockey_to_csv
  File "/opt/airflow/dags/scrape_hocky.py", line 4, in <module>
    import pymongo
ModuleNotFoundError: No module named 'pymongo'
[2024-03-09T01:03:59.017+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag1.py
[2024-03-09T01:03:59.027+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag1.py took 0.057 seconds
[2024-03-09T01:04:29.660+0000] {processor.py:161} INFO - Started process (PID=720) to work on /opt/airflow/dags/dag1.py
[2024-03-09T01:04:29.668+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag1.py for tasks to queue
[2024-03-09T01:04:29.671+0000] {logging_mixin.py:188} INFO - [2024-03-09T01:04:29.670+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/dag1.py
[2024-03-09T01:04:29.716+0000] {logging_mixin.py:188} INFO - [2024-03-09T01:04:29.715+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/dag1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag1.py", line 4, in <module>
    from scrape_hocky import scrape_hockey_data, save_to_csv as save_hockey_to_csv
  File "/opt/airflow/dags/scrape_hocky.py", line 4, in <module>
    import pymongo
ModuleNotFoundError: No module named 'pymongo'
[2024-03-09T01:04:29.716+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag1.py
[2024-03-09T01:04:29.726+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag1.py took 0.070 seconds
[2024-03-09T01:05:00.302+0000] {processor.py:161} INFO - Started process (PID=777) to work on /opt/airflow/dags/dag1.py
[2024-03-09T01:05:00.302+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag1.py for tasks to queue
[2024-03-09T01:05:00.303+0000] {logging_mixin.py:188} INFO - [2024-03-09T01:05:00.303+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/dag1.py
[2024-03-09T01:05:00.337+0000] {logging_mixin.py:188} INFO - [2024-03-09T01:05:00.337+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/dag1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag1.py", line 4, in <module>
    from scrape_hocky import scrape_hockey_data, save_to_csv as save_hockey_to_csv
  File "/opt/airflow/dags/scrape_hocky.py", line 4, in <module>
    import pymongo
ModuleNotFoundError: No module named 'pymongo'
[2024-03-09T01:05:00.337+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag1.py
[2024-03-09T01:05:00.348+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag1.py took 0.048 seconds
[2024-03-09T01:05:30.778+0000] {processor.py:161} INFO - Started process (PID=834) to work on /opt/airflow/dags/dag1.py
[2024-03-09T01:05:30.778+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag1.py for tasks to queue
[2024-03-09T01:05:30.779+0000] {logging_mixin.py:188} INFO - [2024-03-09T01:05:30.779+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/dag1.py
[2024-03-09T01:05:30.817+0000] {logging_mixin.py:188} INFO - [2024-03-09T01:05:30.817+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/dag1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag1.py", line 4, in <module>
    from scrape_hocky import scrape_hockey_data, save_to_csv as save_hockey_to_csv
  File "/opt/airflow/dags/scrape_hocky.py", line 4, in <module>
    import pymongo
ModuleNotFoundError: No module named 'pymongo'
[2024-03-09T01:05:30.817+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag1.py
[2024-03-09T01:05:30.831+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag1.py took 0.056 seconds
[2024-03-09T01:06:01.229+0000] {processor.py:161} INFO - Started process (PID=891) to work on /opt/airflow/dags/dag1.py
[2024-03-09T01:06:01.238+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag1.py for tasks to queue
[2024-03-09T01:06:01.242+0000] {logging_mixin.py:188} INFO - [2024-03-09T01:06:01.241+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/dag1.py
[2024-03-09T01:06:01.289+0000] {logging_mixin.py:188} INFO - [2024-03-09T01:06:01.289+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/dag1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag1.py", line 4, in <module>
    from scrape_hocky import scrape_hockey_data, save_to_csv as save_hockey_to_csv
  File "/opt/airflow/dags/scrape_hocky.py", line 4, in <module>
    import pymongo
ModuleNotFoundError: No module named 'pymongo'
[2024-03-09T01:06:01.289+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag1.py
[2024-03-09T01:06:01.303+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag1.py took 0.078 seconds
[2024-03-09T01:06:31.842+0000] {processor.py:161} INFO - Started process (PID=948) to work on /opt/airflow/dags/dag1.py
[2024-03-09T01:06:31.850+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag1.py for tasks to queue
[2024-03-09T01:06:31.853+0000] {logging_mixin.py:188} INFO - [2024-03-09T01:06:31.853+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/dag1.py
[2024-03-09T01:06:31.898+0000] {logging_mixin.py:188} INFO - [2024-03-09T01:06:31.898+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/dag1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag1.py", line 4, in <module>
    from scrape_hocky import scrape_hockey_data, save_to_csv as save_hockey_to_csv
  File "/opt/airflow/dags/scrape_hocky.py", line 4, in <module>
    import pymongo
ModuleNotFoundError: No module named 'pymongo'
[2024-03-09T01:06:31.898+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag1.py
[2024-03-09T01:06:31.908+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag1.py took 0.069 seconds
[2024-03-09T01:07:02.527+0000] {processor.py:161} INFO - Started process (PID=1005) to work on /opt/airflow/dags/dag1.py
[2024-03-09T01:07:02.529+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag1.py for tasks to queue
[2024-03-09T01:07:02.531+0000] {logging_mixin.py:188} INFO - [2024-03-09T01:07:02.530+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/dag1.py
[2024-03-09T01:07:02.572+0000] {logging_mixin.py:188} INFO - [2024-03-09T01:07:02.572+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/dag1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag1.py", line 4, in <module>
    from scrape_hocky import scrape_hockey_data, save_to_csv as save_hockey_to_csv
  File "/opt/airflow/dags/scrape_hocky.py", line 4, in <module>
    import pymongo
ModuleNotFoundError: No module named 'pymongo'
[2024-03-09T01:07:02.572+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag1.py
[2024-03-09T01:07:02.582+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag1.py took 0.059 seconds
[2024-03-09T01:07:26.714+0000] {processor.py:161} INFO - Started process (PID=1012) to work on /opt/airflow/dags/dag1.py
[2024-03-09T01:07:26.716+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag1.py for tasks to queue
[2024-03-09T01:07:26.719+0000] {logging_mixin.py:188} INFO - [2024-03-09T01:07:26.718+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/dag1.py
[2024-03-09T01:07:26.762+0000] {logging_mixin.py:188} INFO - [2024-03-09T01:07:26.761+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/dag1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag1.py", line 4, in <module>
    from scrape_hocky import scrape_hockey_data, save_to_csv as save_hockey_to_csv
  File "/opt/airflow/dags/scrape_hocky.py", line 4, in <module>
    import pymongo
ModuleNotFoundError: No module named 'pymongo'
[2024-03-09T01:07:26.762+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag1.py
[2024-03-09T01:07:26.773+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag1.py took 0.065 seconds
[2024-03-09T01:07:57.541+0000] {processor.py:161} INFO - Started process (PID=1070) to work on /opt/airflow/dags/dag1.py
[2024-03-09T01:07:57.550+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag1.py for tasks to queue
[2024-03-09T01:07:57.554+0000] {logging_mixin.py:188} INFO - [2024-03-09T01:07:57.553+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/dag1.py
[2024-03-09T01:07:57.602+0000] {logging_mixin.py:188} INFO - [2024-03-09T01:07:57.601+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/dag1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag1.py", line 4, in <module>
    from scrape_hocky import scrape_hockey_data, save_to_csv as save_hockey_to_csv
  File "/opt/airflow/dags/scrape_hocky.py", line 4, in <module>
    import pymongo
ModuleNotFoundError: No module named 'pymongo'
[2024-03-09T01:07:57.602+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag1.py
[2024-03-09T01:07:57.614+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag1.py took 0.080 seconds
[2024-03-09T01:08:28.264+0000] {processor.py:161} INFO - Started process (PID=1127) to work on /opt/airflow/dags/dag1.py
[2024-03-09T01:08:28.273+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag1.py for tasks to queue
[2024-03-09T01:08:28.277+0000] {logging_mixin.py:188} INFO - [2024-03-09T01:08:28.276+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/dag1.py
[2024-03-09T01:08:28.331+0000] {logging_mixin.py:188} INFO - [2024-03-09T01:08:28.330+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/dag1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag1.py", line 4, in <module>
    from scrape_hocky import scrape_hockey_data, save_to_csv as save_hockey_to_csv
  File "/opt/airflow/dags/scrape_hocky.py", line 4, in <module>
    import pymongo
ModuleNotFoundError: No module named 'pymongo'
[2024-03-09T01:08:28.331+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag1.py
[2024-03-09T01:08:28.343+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag1.py took 0.082 seconds
[2024-03-09T01:08:59.042+0000] {processor.py:161} INFO - Started process (PID=1184) to work on /opt/airflow/dags/dag1.py
[2024-03-09T01:08:59.051+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag1.py for tasks to queue
[2024-03-09T01:08:59.054+0000] {logging_mixin.py:188} INFO - [2024-03-09T01:08:59.054+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/dag1.py
[2024-03-09T01:08:59.097+0000] {logging_mixin.py:188} INFO - [2024-03-09T01:08:59.096+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/dag1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag1.py", line 4, in <module>
    from scrape_hocky import scrape_hockey_data, save_to_csv as save_hockey_to_csv
  File "/opt/airflow/dags/scrape_hocky.py", line 4, in <module>
    import pymongo
ModuleNotFoundError: No module named 'pymongo'
[2024-03-09T01:08:59.097+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag1.py
[2024-03-09T01:08:59.106+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag1.py took 0.067 seconds
[2024-03-09T01:09:29.658+0000] {processor.py:161} INFO - Started process (PID=1241) to work on /opt/airflow/dags/dag1.py
[2024-03-09T01:09:29.667+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag1.py for tasks to queue
[2024-03-09T01:09:29.670+0000] {logging_mixin.py:188} INFO - [2024-03-09T01:09:29.670+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/dag1.py
[2024-03-09T01:09:29.713+0000] {logging_mixin.py:188} INFO - [2024-03-09T01:09:29.713+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/dag1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag1.py", line 4, in <module>
    from scrape_hocky import scrape_hockey_data, save_to_csv as save_hockey_to_csv
  File "/opt/airflow/dags/scrape_hocky.py", line 4, in <module>
    import pymongo
ModuleNotFoundError: No module named 'pymongo'
[2024-03-09T01:09:29.714+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag1.py
[2024-03-09T01:09:29.723+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag1.py took 0.068 seconds
[2024-03-09T01:10:00.144+0000] {processor.py:161} INFO - Started process (PID=1298) to work on /opt/airflow/dags/dag1.py
[2024-03-09T01:10:00.152+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag1.py for tasks to queue
[2024-03-09T01:10:00.155+0000] {logging_mixin.py:188} INFO - [2024-03-09T01:10:00.155+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/dag1.py
[2024-03-09T01:10:00.199+0000] {logging_mixin.py:188} INFO - [2024-03-09T01:10:00.199+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/dag1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag1.py", line 4, in <module>
    from scrape_hocky import scrape_hockey_data, save_to_csv as save_hockey_to_csv
  File "/opt/airflow/dags/scrape_hocky.py", line 4, in <module>
    import pymongo
ModuleNotFoundError: No module named 'pymongo'
[2024-03-09T01:10:00.199+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag1.py
[2024-03-09T01:10:00.209+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag1.py took 0.068 seconds
[2024-03-09T01:10:30.796+0000] {processor.py:161} INFO - Started process (PID=1355) to work on /opt/airflow/dags/dag1.py
[2024-03-09T01:10:30.805+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag1.py for tasks to queue
[2024-03-09T01:10:30.808+0000] {logging_mixin.py:188} INFO - [2024-03-09T01:10:30.808+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/dag1.py
[2024-03-09T01:10:30.857+0000] {logging_mixin.py:188} INFO - [2024-03-09T01:10:30.856+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/dag1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag1.py", line 4, in <module>
    from scrape_hocky import scrape_hockey_data, save_to_csv as save_hockey_to_csv
  File "/opt/airflow/dags/scrape_hocky.py", line 4, in <module>
    import pymongo
ModuleNotFoundError: No module named 'pymongo'
[2024-03-09T01:10:30.857+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag1.py
[2024-03-09T01:10:30.874+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag1.py took 0.082 seconds
[2024-03-09T01:11:01.447+0000] {processor.py:161} INFO - Started process (PID=1412) to work on /opt/airflow/dags/dag1.py
[2024-03-09T01:11:01.449+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag1.py for tasks to queue
[2024-03-09T01:11:01.452+0000] {logging_mixin.py:188} INFO - [2024-03-09T01:11:01.451+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/dag1.py
[2024-03-09T01:11:01.497+0000] {logging_mixin.py:188} INFO - [2024-03-09T01:11:01.497+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/dag1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag1.py", line 4, in <module>
    from scrape_hocky import scrape_hockey_data, save_to_csv as save_hockey_to_csv
  File "/opt/airflow/dags/scrape_hocky.py", line 4, in <module>
    import pymongo
ModuleNotFoundError: No module named 'pymongo'
[2024-03-09T01:11:01.497+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag1.py
[2024-03-09T01:11:01.512+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag1.py took 0.068 seconds
[2024-03-09T01:11:31.979+0000] {processor.py:161} INFO - Started process (PID=1469) to work on /opt/airflow/dags/dag1.py
[2024-03-09T01:11:31.988+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag1.py for tasks to queue
[2024-03-09T01:11:31.990+0000] {logging_mixin.py:188} INFO - [2024-03-09T01:11:31.990+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/dag1.py
[2024-03-09T01:11:32.035+0000] {logging_mixin.py:188} INFO - [2024-03-09T01:11:32.034+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/dag1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag1.py", line 4, in <module>
    from scrape_hocky import scrape_hockey_data, save_to_csv as save_hockey_to_csv
  File "/opt/airflow/dags/scrape_hocky.py", line 4, in <module>
    import pymongo
ModuleNotFoundError: No module named 'pymongo'
[2024-03-09T01:11:32.035+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag1.py
[2024-03-09T01:11:32.044+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag1.py took 0.070 seconds
[2024-03-09T01:12:02.570+0000] {processor.py:161} INFO - Started process (PID=1526) to work on /opt/airflow/dags/dag1.py
[2024-03-09T01:12:02.579+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag1.py for tasks to queue
[2024-03-09T01:12:02.582+0000] {logging_mixin.py:188} INFO - [2024-03-09T01:12:02.581+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/dag1.py
[2024-03-09T01:12:02.629+0000] {logging_mixin.py:188} INFO - [2024-03-09T01:12:02.628+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/dag1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag1.py", line 4, in <module>
    from scrape_hocky import scrape_hockey_data, save_to_csv as save_hockey_to_csv
  File "/opt/airflow/dags/scrape_hocky.py", line 4, in <module>
    import pymongo
ModuleNotFoundError: No module named 'pymongo'
[2024-03-09T01:12:02.629+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag1.py
[2024-03-09T01:12:02.642+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag1.py took 0.076 seconds
[2024-03-09T01:12:33.135+0000] {processor.py:161} INFO - Started process (PID=1583) to work on /opt/airflow/dags/dag1.py
[2024-03-09T01:12:33.137+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag1.py for tasks to queue
[2024-03-09T01:12:33.139+0000] {logging_mixin.py:188} INFO - [2024-03-09T01:12:33.139+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/dag1.py
[2024-03-09T01:12:33.187+0000] {logging_mixin.py:188} INFO - [2024-03-09T01:12:33.187+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/dag1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag1.py", line 4, in <module>
    from scrape_hocky import scrape_hockey_data, save_to_csv as save_hockey_to_csv
  File "/opt/airflow/dags/scrape_hocky.py", line 4, in <module>
    import pymongo
ModuleNotFoundError: No module named 'pymongo'
[2024-03-09T01:12:33.188+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag1.py
[2024-03-09T01:12:33.198+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag1.py took 0.067 seconds
[2024-03-09T01:13:03.811+0000] {processor.py:161} INFO - Started process (PID=1640) to work on /opt/airflow/dags/dag1.py
[2024-03-09T01:13:03.819+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag1.py for tasks to queue
[2024-03-09T01:13:03.822+0000] {logging_mixin.py:188} INFO - [2024-03-09T01:13:03.822+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/dag1.py
[2024-03-09T01:13:03.870+0000] {logging_mixin.py:188} INFO - [2024-03-09T01:13:03.869+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/dag1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag1.py", line 4, in <module>
    from scrape_hocky import scrape_hockey_data, save_to_csv as save_hockey_to_csv
  File "/opt/airflow/dags/scrape_hocky.py", line 4, in <module>
    import pymongo
ModuleNotFoundError: No module named 'pymongo'
[2024-03-09T01:13:03.870+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag1.py
[2024-03-09T01:13:03.884+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag1.py took 0.076 seconds
[2024-03-09T01:13:34.364+0000] {processor.py:161} INFO - Started process (PID=1697) to work on /opt/airflow/dags/dag1.py
[2024-03-09T01:13:34.373+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag1.py for tasks to queue
[2024-03-09T01:13:34.377+0000] {logging_mixin.py:188} INFO - [2024-03-09T01:13:34.376+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/dag1.py
[2024-03-09T01:13:34.425+0000] {logging_mixin.py:188} INFO - [2024-03-09T01:13:34.424+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/dag1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag1.py", line 4, in <module>
    from scrape_hocky import scrape_hockey_data, save_to_csv as save_hockey_to_csv
  File "/opt/airflow/dags/scrape_hocky.py", line 4, in <module>
    import pymongo
ModuleNotFoundError: No module named 'pymongo'
[2024-03-09T01:13:34.425+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag1.py
[2024-03-09T01:13:34.439+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag1.py took 0.078 seconds
[2024-03-09T01:14:04.940+0000] {processor.py:161} INFO - Started process (PID=1754) to work on /opt/airflow/dags/dag1.py
[2024-03-09T01:14:04.941+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag1.py for tasks to queue
[2024-03-09T01:14:04.943+0000] {logging_mixin.py:188} INFO - [2024-03-09T01:14:04.943+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/dag1.py
[2024-03-09T01:14:04.983+0000] {logging_mixin.py:188} INFO - [2024-03-09T01:14:04.982+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/dag1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag1.py", line 4, in <module>
    from scrape_hocky import scrape_hockey_data, save_to_csv as save_hockey_to_csv
  File "/opt/airflow/dags/scrape_hocky.py", line 4, in <module>
    import pymongo
ModuleNotFoundError: No module named 'pymongo'
[2024-03-09T01:14:04.983+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag1.py
[2024-03-09T01:14:04.996+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag1.py took 0.060 seconds
[2024-03-09T01:14:35.495+0000] {processor.py:161} INFO - Started process (PID=1811) to work on /opt/airflow/dags/dag1.py
[2024-03-09T01:14:35.497+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag1.py for tasks to queue
[2024-03-09T01:14:35.499+0000] {logging_mixin.py:188} INFO - [2024-03-09T01:14:35.498+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/dag1.py
[2024-03-09T01:14:35.532+0000] {logging_mixin.py:188} INFO - [2024-03-09T01:14:35.532+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/dag1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag1.py", line 4, in <module>
    from scrape_hocky import scrape_hockey_data, save_to_csv as save_hockey_to_csv
  File "/opt/airflow/dags/scrape_hocky.py", line 4, in <module>
    import pymongo
ModuleNotFoundError: No module named 'pymongo'
[2024-03-09T01:14:35.532+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag1.py
[2024-03-09T01:14:35.541+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag1.py took 0.048 seconds
[2024-03-09T01:15:06.035+0000] {processor.py:161} INFO - Started process (PID=1869) to work on /opt/airflow/dags/dag1.py
[2024-03-09T01:15:06.043+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag1.py for tasks to queue
[2024-03-09T01:15:06.047+0000] {logging_mixin.py:188} INFO - [2024-03-09T01:15:06.046+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/dag1.py
[2024-03-09T01:15:06.110+0000] {logging_mixin.py:188} INFO - [2024-03-09T01:15:06.109+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/dag1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag1.py", line 4, in <module>
    from scrape_hocky import scrape_hockey_data, save_to_csv as save_hockey_to_csv
  File "/opt/airflow/dags/scrape_hocky.py", line 4, in <module>
    import pymongo
ModuleNotFoundError: No module named 'pymongo'
[2024-03-09T01:15:06.110+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag1.py
[2024-03-09T01:15:06.123+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag1.py took 0.092 seconds
[2024-03-09T01:15:36.613+0000] {processor.py:161} INFO - Started process (PID=1926) to work on /opt/airflow/dags/dag1.py
[2024-03-09T01:15:36.622+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag1.py for tasks to queue
[2024-03-09T01:15:36.625+0000] {logging_mixin.py:188} INFO - [2024-03-09T01:15:36.625+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/dag1.py
[2024-03-09T01:15:36.670+0000] {logging_mixin.py:188} INFO - [2024-03-09T01:15:36.669+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/dag1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag1.py", line 4, in <module>
    from scrape_hocky import scrape_hockey_data, save_to_csv as save_hockey_to_csv
  File "/opt/airflow/dags/scrape_hocky.py", line 4, in <module>
    import pymongo
ModuleNotFoundError: No module named 'pymongo'
[2024-03-09T01:15:36.670+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag1.py
[2024-03-09T01:15:36.679+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag1.py took 0.070 seconds
[2024-03-09T01:16:07.339+0000] {processor.py:161} INFO - Started process (PID=1983) to work on /opt/airflow/dags/dag1.py
[2024-03-09T01:16:07.348+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag1.py for tasks to queue
[2024-03-09T01:16:07.353+0000] {logging_mixin.py:188} INFO - [2024-03-09T01:16:07.352+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/dag1.py
[2024-03-09T01:16:07.410+0000] {logging_mixin.py:188} INFO - [2024-03-09T01:16:07.410+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/dag1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag1.py", line 4, in <module>
    from scrape_hocky import scrape_hockey_data, save_to_csv as save_hockey_to_csv
  File "/opt/airflow/dags/scrape_hocky.py", line 4, in <module>
    import pymongo
ModuleNotFoundError: No module named 'pymongo'
[2024-03-09T01:16:07.411+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag1.py
[2024-03-09T01:16:07.424+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag1.py took 0.088 seconds
[2024-03-09T01:16:37.829+0000] {processor.py:161} INFO - Started process (PID=2040) to work on /opt/airflow/dags/dag1.py
[2024-03-09T01:16:37.831+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag1.py for tasks to queue
[2024-03-09T01:16:37.834+0000] {logging_mixin.py:188} INFO - [2024-03-09T01:16:37.833+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/dag1.py
[2024-03-09T01:16:37.880+0000] {logging_mixin.py:188} INFO - [2024-03-09T01:16:37.880+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/dag1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag1.py", line 4, in <module>
    from scrape_hocky import scrape_hockey_data, save_to_csv as save_hockey_to_csv
  File "/opt/airflow/dags/scrape_hocky.py", line 4, in <module>
    import pymongo
ModuleNotFoundError: No module named 'pymongo'
[2024-03-09T01:16:37.881+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag1.py
[2024-03-09T01:16:37.894+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag1.py took 0.070 seconds
[2024-03-09T01:17:08.292+0000] {processor.py:161} INFO - Started process (PID=2097) to work on /opt/airflow/dags/dag1.py
[2024-03-09T01:17:08.301+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag1.py for tasks to queue
[2024-03-09T01:17:08.302+0000] {logging_mixin.py:188} INFO - [2024-03-09T01:17:08.302+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/dag1.py
[2024-03-09T01:17:08.345+0000] {logging_mixin.py:188} INFO - [2024-03-09T01:17:08.344+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/dag1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag1.py", line 4, in <module>
    from scrape_hocky import scrape_hockey_data, save_to_csv as save_hockey_to_csv
  File "/opt/airflow/dags/scrape_hocky.py", line 4, in <module>
    import pymongo
ModuleNotFoundError: No module named 'pymongo'
[2024-03-09T01:17:08.345+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag1.py
[2024-03-09T01:17:08.355+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag1.py took 0.066 seconds
[2024-03-09T01:17:38.869+0000] {processor.py:161} INFO - Started process (PID=2154) to work on /opt/airflow/dags/dag1.py
[2024-03-09T01:17:38.870+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag1.py for tasks to queue
[2024-03-09T01:17:38.872+0000] {logging_mixin.py:188} INFO - [2024-03-09T01:17:38.872+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/dag1.py
[2024-03-09T01:17:38.920+0000] {logging_mixin.py:188} INFO - [2024-03-09T01:17:38.919+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/dag1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag1.py", line 4, in <module>
    from scrape_hocky import scrape_hockey_data, save_to_csv as save_hockey_to_csv
  File "/opt/airflow/dags/scrape_hocky.py", line 4, in <module>
    import pymongo
ModuleNotFoundError: No module named 'pymongo'
[2024-03-09T01:17:38.920+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag1.py
[2024-03-09T01:17:38.935+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag1.py took 0.069 seconds
[2024-03-09T01:18:09.358+0000] {processor.py:161} INFO - Started process (PID=2211) to work on /opt/airflow/dags/dag1.py
[2024-03-09T01:18:09.367+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag1.py for tasks to queue
[2024-03-09T01:18:09.370+0000] {logging_mixin.py:188} INFO - [2024-03-09T01:18:09.370+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/dag1.py
[2024-03-09T01:18:09.419+0000] {logging_mixin.py:188} INFO - [2024-03-09T01:18:09.419+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/dag1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag1.py", line 4, in <module>
    from scrape_hocky import scrape_hockey_data, save_to_csv as save_hockey_to_csv
  File "/opt/airflow/dags/scrape_hocky.py", line 4, in <module>
    import pymongo
ModuleNotFoundError: No module named 'pymongo'
[2024-03-09T01:18:09.420+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag1.py
[2024-03-09T01:18:09.433+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag1.py took 0.079 seconds
[2024-03-09T01:18:39.923+0000] {processor.py:161} INFO - Started process (PID=2268) to work on /opt/airflow/dags/dag1.py
[2024-03-09T01:18:39.932+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag1.py for tasks to queue
[2024-03-09T01:18:39.935+0000] {logging_mixin.py:188} INFO - [2024-03-09T01:18:39.934+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/dag1.py
[2024-03-09T01:18:39.979+0000] {logging_mixin.py:188} INFO - [2024-03-09T01:18:39.979+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/dag1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag1.py", line 4, in <module>
    from scrape_hocky import scrape_hockey_data, save_to_csv as save_hockey_to_csv
  File "/opt/airflow/dags/scrape_hocky.py", line 4, in <module>
    import pymongo
ModuleNotFoundError: No module named 'pymongo'
[2024-03-09T01:18:39.979+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag1.py
[2024-03-09T01:18:39.989+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag1.py took 0.070 seconds
[2024-03-09T01:19:10.591+0000] {processor.py:161} INFO - Started process (PID=2326) to work on /opt/airflow/dags/dag1.py
[2024-03-09T01:19:10.600+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag1.py for tasks to queue
[2024-03-09T01:19:10.603+0000] {logging_mixin.py:188} INFO - [2024-03-09T01:19:10.603+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/dag1.py
[2024-03-09T01:19:10.649+0000] {logging_mixin.py:188} INFO - [2024-03-09T01:19:10.648+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/dag1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag1.py", line 4, in <module>
    from scrape_hocky import scrape_hockey_data, save_to_csv as save_hockey_to_csv
  File "/opt/airflow/dags/scrape_hocky.py", line 4, in <module>
    import pymongo
ModuleNotFoundError: No module named 'pymongo'
[2024-03-09T01:19:10.649+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag1.py
[2024-03-09T01:19:10.663+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag1.py took 0.075 seconds
[2024-03-09T01:19:41.083+0000] {processor.py:161} INFO - Started process (PID=2383) to work on /opt/airflow/dags/dag1.py
[2024-03-09T01:19:41.092+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag1.py for tasks to queue
[2024-03-09T01:19:41.095+0000] {logging_mixin.py:188} INFO - [2024-03-09T01:19:41.094+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/dag1.py
[2024-03-09T01:19:41.143+0000] {logging_mixin.py:188} INFO - [2024-03-09T01:19:41.143+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/dag1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag1.py", line 4, in <module>
    from scrape_hocky import scrape_hockey_data, save_to_csv as save_hockey_to_csv
  File "/opt/airflow/dags/scrape_hocky.py", line 4, in <module>
    import pymongo
ModuleNotFoundError: No module named 'pymongo'
[2024-03-09T01:19:41.144+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag1.py
[2024-03-09T01:19:41.157+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag1.py took 0.079 seconds
[2024-03-09T01:20:11.629+0000] {processor.py:161} INFO - Started process (PID=2440) to work on /opt/airflow/dags/dag1.py
[2024-03-09T01:20:11.638+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag1.py for tasks to queue
[2024-03-09T01:20:11.642+0000] {logging_mixin.py:188} INFO - [2024-03-09T01:20:11.641+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/dag1.py
[2024-03-09T01:20:11.690+0000] {logging_mixin.py:188} INFO - [2024-03-09T01:20:11.689+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/dag1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag1.py", line 4, in <module>
    from scrape_hocky import scrape_hockey_data, save_to_csv as save_hockey_to_csv
  File "/opt/airflow/dags/scrape_hocky.py", line 4, in <module>
    import pymongo
ModuleNotFoundError: No module named 'pymongo'
[2024-03-09T01:20:11.690+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag1.py
[2024-03-09T01:20:11.703+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag1.py took 0.080 seconds
[2024-03-09T01:20:42.253+0000] {processor.py:161} INFO - Started process (PID=2497) to work on /opt/airflow/dags/dag1.py
[2024-03-09T01:20:42.262+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag1.py for tasks to queue
[2024-03-09T01:20:42.264+0000] {logging_mixin.py:188} INFO - [2024-03-09T01:20:42.264+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/dag1.py
[2024-03-09T01:20:42.304+0000] {logging_mixin.py:188} INFO - [2024-03-09T01:20:42.304+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/dag1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag1.py", line 4, in <module>
    from scrape_hocky import scrape_hockey_data, save_to_csv as save_hockey_to_csv
  File "/opt/airflow/dags/scrape_hocky.py", line 4, in <module>
    import pymongo
ModuleNotFoundError: No module named 'pymongo'
[2024-03-09T01:20:42.304+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag1.py
[2024-03-09T01:20:42.313+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag1.py took 0.065 seconds
[2024-03-09T01:21:12.892+0000] {processor.py:161} INFO - Started process (PID=2560) to work on /opt/airflow/dags/dag1.py
[2024-03-09T01:21:12.901+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag1.py for tasks to queue
[2024-03-09T01:21:12.904+0000] {logging_mixin.py:188} INFO - [2024-03-09T01:21:12.904+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/dag1.py
[2024-03-09T01:21:12.953+0000] {logging_mixin.py:188} INFO - [2024-03-09T01:21:12.952+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/dag1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag1.py", line 4, in <module>
    from scrape_hocky import scrape_hockey_data, save_to_csv as save_hockey_to_csv
  File "/opt/airflow/dags/scrape_hocky.py", line 4, in <module>
    import pymongo
ModuleNotFoundError: No module named 'pymongo'
[2024-03-09T01:21:12.953+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag1.py
[2024-03-09T01:21:12.963+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag1.py took 0.074 seconds
[2024-03-09T01:21:43.388+0000] {processor.py:161} INFO - Started process (PID=2617) to work on /opt/airflow/dags/dag1.py
[2024-03-09T01:21:43.398+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag1.py for tasks to queue
[2024-03-09T01:21:43.401+0000] {logging_mixin.py:188} INFO - [2024-03-09T01:21:43.401+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/dag1.py
[2024-03-09T01:21:43.446+0000] {logging_mixin.py:188} INFO - [2024-03-09T01:21:43.445+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/dag1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag1.py", line 4, in <module>
    from scrape_hocky import scrape_hockey_data, save_to_csv as save_hockey_to_csv
  File "/opt/airflow/dags/scrape_hocky.py", line 4, in <module>
    import pymongo
ModuleNotFoundError: No module named 'pymongo'
[2024-03-09T01:21:43.446+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag1.py
[2024-03-09T01:21:43.455+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag1.py took 0.072 seconds
[2024-03-09T01:22:26.543+0000] {processor.py:161} INFO - Started process (PID=44) to work on /opt/airflow/dags/dag1.py
[2024-03-09T01:22:26.544+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag1.py for tasks to queue
[2024-03-09T01:22:26.546+0000] {logging_mixin.py:188} INFO - [2024-03-09T01:22:26.545+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/dag1.py
[2024-03-09T01:22:26.613+0000] {logging_mixin.py:188} INFO - [2024-03-09T01:22:26.612+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/dag1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag1.py", line 4, in <module>
    from scrape_hocky import scrape_hockey_data, save_to_csv as save_hockey_to_csv
  File "/opt/airflow/dags/scrape_hocky.py", line 4, in <module>
    import pymongo
ModuleNotFoundError: No module named 'pymongo'
[2024-03-09T01:22:26.613+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag1.py
[2024-03-09T01:22:26.628+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag1.py took 0.088 seconds
[2024-03-09T01:22:57.367+0000] {processor.py:161} INFO - Started process (PID=101) to work on /opt/airflow/dags/dag1.py
[2024-03-09T01:22:57.368+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag1.py for tasks to queue
[2024-03-09T01:22:57.369+0000] {logging_mixin.py:188} INFO - [2024-03-09T01:22:57.369+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/dag1.py
[2024-03-09T01:22:57.408+0000] {logging_mixin.py:188} INFO - [2024-03-09T01:22:57.407+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/dag1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag1.py", line 4, in <module>
    from scrape_hocky import scrape_hockey_data, save_to_csv as save_hockey_to_csv
  File "/opt/airflow/dags/scrape_hocky.py", line 4, in <module>
    import pymongo
ModuleNotFoundError: No module named 'pymongo'
[2024-03-09T01:22:57.408+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag1.py
[2024-03-09T01:22:57.418+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag1.py took 0.054 seconds
[2024-03-09T01:23:27.783+0000] {processor.py:161} INFO - Started process (PID=158) to work on /opt/airflow/dags/dag1.py
[2024-03-09T01:23:27.785+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag1.py for tasks to queue
[2024-03-09T01:23:27.786+0000] {logging_mixin.py:188} INFO - [2024-03-09T01:23:27.786+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/dag1.py
[2024-03-09T01:23:27.830+0000] {logging_mixin.py:188} INFO - [2024-03-09T01:23:27.829+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/dag1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag1.py", line 4, in <module>
    from scrape_hocky import scrape_hockey_data, save_to_csv as save_hockey_to_csv
  File "/opt/airflow/dags/scrape_hocky.py", line 4, in <module>
    import pymongo
ModuleNotFoundError: No module named 'pymongo'
[2024-03-09T01:23:27.830+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag1.py
[2024-03-09T01:23:27.840+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag1.py took 0.061 seconds
[2024-03-09T01:23:58.513+0000] {processor.py:161} INFO - Started process (PID=215) to work on /opt/airflow/dags/dag1.py
[2024-03-09T01:23:58.515+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag1.py for tasks to queue
[2024-03-09T01:23:58.517+0000] {logging_mixin.py:188} INFO - [2024-03-09T01:23:58.516+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/dag1.py
[2024-03-09T01:23:58.559+0000] {logging_mixin.py:188} INFO - [2024-03-09T01:23:58.558+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/dag1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag1.py", line 4, in <module>
    from scrape_hocky import scrape_hockey_data, save_to_csv as save_hockey_to_csv
  File "/opt/airflow/dags/scrape_hocky.py", line 4, in <module>
    import pymongo
ModuleNotFoundError: No module named 'pymongo'
[2024-03-09T01:23:58.559+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag1.py
[2024-03-09T01:23:58.569+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag1.py took 0.059 seconds
[2024-03-09T01:24:29.199+0000] {processor.py:161} INFO - Started process (PID=272) to work on /opt/airflow/dags/dag1.py
[2024-03-09T01:24:29.202+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag1.py for tasks to queue
[2024-03-09T01:24:29.203+0000] {logging_mixin.py:188} INFO - [2024-03-09T01:24:29.203+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/dag1.py
[2024-03-09T01:24:29.251+0000] {logging_mixin.py:188} INFO - [2024-03-09T01:24:29.250+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/dag1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag1.py", line 4, in <module>
    from scrape_hocky import scrape_hockey_data, save_to_csv as save_hockey_to_csv
  File "/opt/airflow/dags/scrape_hocky.py", line 4, in <module>
    import pymongo
ModuleNotFoundError: No module named 'pymongo'
[2024-03-09T01:24:29.251+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag1.py
[2024-03-09T01:24:29.260+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag1.py took 0.065 seconds
[2024-03-09T01:24:59.720+0000] {processor.py:161} INFO - Started process (PID=329) to work on /opt/airflow/dags/dag1.py
[2024-03-09T01:24:59.722+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag1.py for tasks to queue
[2024-03-09T01:24:59.723+0000] {logging_mixin.py:188} INFO - [2024-03-09T01:24:59.723+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/dag1.py
[2024-03-09T01:24:59.772+0000] {logging_mixin.py:188} INFO - [2024-03-09T01:24:59.771+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/dag1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag1.py", line 4, in <module>
    from scrape_hocky import scrape_hockey_data, save_to_csv as save_hockey_to_csv
  File "/opt/airflow/dags/scrape_hocky.py", line 4, in <module>
    import pymongo
ModuleNotFoundError: No module named 'pymongo'
[2024-03-09T01:24:59.772+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag1.py
[2024-03-09T01:24:59.784+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag1.py took 0.067 seconds
[2024-03-09T01:25:30.304+0000] {processor.py:161} INFO - Started process (PID=386) to work on /opt/airflow/dags/dag1.py
[2024-03-09T01:25:30.309+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag1.py for tasks to queue
[2024-03-09T01:25:30.310+0000] {logging_mixin.py:188} INFO - [2024-03-09T01:25:30.310+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/dag1.py
[2024-03-09T01:25:30.356+0000] {logging_mixin.py:188} INFO - [2024-03-09T01:25:30.356+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/dag1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag1.py", line 4, in <module>
    from scrape_hocky import scrape_hockey_data, save_to_csv as save_hockey_to_csv
  File "/opt/airflow/dags/scrape_hocky.py", line 4, in <module>
    import pymongo
ModuleNotFoundError: No module named 'pymongo'
[2024-03-09T01:25:30.357+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag1.py
[2024-03-09T01:25:30.366+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag1.py took 0.065 seconds
[2024-03-09T01:26:00.759+0000] {processor.py:161} INFO - Started process (PID=443) to work on /opt/airflow/dags/dag1.py
[2024-03-09T01:26:00.761+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag1.py for tasks to queue
[2024-03-09T01:26:00.762+0000] {logging_mixin.py:188} INFO - [2024-03-09T01:26:00.762+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/dag1.py
[2024-03-09T01:26:00.807+0000] {logging_mixin.py:188} INFO - [2024-03-09T01:26:00.806+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/dag1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag1.py", line 4, in <module>
    from scrape_hocky import scrape_hockey_data, save_to_csv as save_hockey_to_csv
  File "/opt/airflow/dags/scrape_hocky.py", line 4, in <module>
    import pymongo
ModuleNotFoundError: No module named 'pymongo'
[2024-03-09T01:26:00.807+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag1.py
[2024-03-09T01:26:00.818+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag1.py took 0.062 seconds
[2024-03-09T01:26:31.289+0000] {processor.py:161} INFO - Started process (PID=500) to work on /opt/airflow/dags/dag1.py
[2024-03-09T01:26:31.290+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag1.py for tasks to queue
[2024-03-09T01:26:31.291+0000] {logging_mixin.py:188} INFO - [2024-03-09T01:26:31.291+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/dag1.py
[2024-03-09T01:26:31.333+0000] {logging_mixin.py:188} INFO - [2024-03-09T01:26:31.332+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/dag1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag1.py", line 4, in <module>
    from scrape_hocky import scrape_hockey_data, save_to_csv as save_hockey_to_csv
  File "/opt/airflow/dags/scrape_hocky.py", line 4, in <module>
    import pymongo
ModuleNotFoundError: No module named 'pymongo'
[2024-03-09T01:26:31.333+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag1.py
[2024-03-09T01:26:31.343+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag1.py took 0.055 seconds
[2024-03-09T01:27:01.769+0000] {processor.py:161} INFO - Started process (PID=557) to work on /opt/airflow/dags/dag1.py
[2024-03-09T01:27:01.770+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag1.py for tasks to queue
[2024-03-09T01:27:01.771+0000] {logging_mixin.py:188} INFO - [2024-03-09T01:27:01.770+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/dag1.py
[2024-03-09T01:27:01.809+0000] {logging_mixin.py:188} INFO - [2024-03-09T01:27:01.809+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/dag1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag1.py", line 4, in <module>
    from scrape_hocky import scrape_hockey_data, save_to_csv as save_hockey_to_csv
  File "/opt/airflow/dags/scrape_hocky.py", line 4, in <module>
    import pymongo
ModuleNotFoundError: No module named 'pymongo'
[2024-03-09T01:27:01.809+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag1.py
[2024-03-09T01:27:01.820+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag1.py took 0.052 seconds
[2024-03-09T01:27:32.407+0000] {processor.py:161} INFO - Started process (PID=614) to work on /opt/airflow/dags/dag1.py
[2024-03-09T01:27:32.410+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag1.py for tasks to queue
[2024-03-09T01:27:32.411+0000] {logging_mixin.py:188} INFO - [2024-03-09T01:27:32.411+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/dag1.py
[2024-03-09T01:27:32.451+0000] {logging_mixin.py:188} INFO - [2024-03-09T01:27:32.450+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/dag1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag1.py", line 4, in <module>
    from scrape_hocky import scrape_hockey_data, save_to_csv as save_hockey_to_csv
  File "/opt/airflow/dags/scrape_hocky.py", line 4, in <module>
    import pymongo
ModuleNotFoundError: No module named 'pymongo'
[2024-03-09T01:27:32.451+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag1.py
[2024-03-09T01:27:32.464+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag1.py took 0.059 seconds
[2024-03-09T01:28:29.531+0000] {processor.py:161} INFO - Started process (PID=43) to work on /opt/airflow/dags/dag1.py
[2024-03-09T01:28:29.532+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag1.py for tasks to queue
[2024-03-09T01:28:29.534+0000] {logging_mixin.py:188} INFO - [2024-03-09T01:28:29.534+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/dag1.py
[2024-03-09T01:28:29.660+0000] {logging_mixin.py:188} INFO - [2024-03-09T01:28:29.659+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/dag1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag1.py", line 4, in <module>
    from scrape_hocky import scrape_hockey_data, save_to_csv as save_hockey_to_csv
  File "/opt/airflow/dags/scrape_hocky.py", line 4, in <module>
    import pymongo
ModuleNotFoundError: No module named 'pymongo'
[2024-03-09T01:28:29.660+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag1.py
[2024-03-09T01:28:29.676+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag1.py took 0.149 seconds
[2024-03-09T01:29:00.064+0000] {processor.py:161} INFO - Started process (PID=100) to work on /opt/airflow/dags/dag1.py
[2024-03-09T01:29:00.065+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag1.py for tasks to queue
[2024-03-09T01:29:00.066+0000] {logging_mixin.py:188} INFO - [2024-03-09T01:29:00.066+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/dag1.py
[2024-03-09T01:29:00.106+0000] {logging_mixin.py:188} INFO - [2024-03-09T01:29:00.105+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/dag1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag1.py", line 4, in <module>
    from scrape_hocky import scrape_hockey_data, save_to_csv as save_hockey_to_csv
  File "/opt/airflow/dags/scrape_hocky.py", line 4, in <module>
    import pymongo
ModuleNotFoundError: No module named 'pymongo'
[2024-03-09T01:29:00.106+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag1.py
[2024-03-09T01:29:00.116+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag1.py took 0.054 seconds
[2024-03-09T01:29:30.538+0000] {processor.py:161} INFO - Started process (PID=157) to work on /opt/airflow/dags/dag1.py
[2024-03-09T01:29:30.540+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag1.py for tasks to queue
[2024-03-09T01:29:30.542+0000] {logging_mixin.py:188} INFO - [2024-03-09T01:29:30.541+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/dag1.py
[2024-03-09T01:29:30.588+0000] {logging_mixin.py:188} INFO - [2024-03-09T01:29:30.588+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/dag1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag1.py", line 4, in <module>
    from scrape_hocky import scrape_hockey_data, save_to_csv as save_hockey_to_csv
  File "/opt/airflow/dags/scrape_hocky.py", line 4, in <module>
    import pymongo
ModuleNotFoundError: No module named 'pymongo'
[2024-03-09T01:29:30.589+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag1.py
[2024-03-09T01:29:30.601+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag1.py took 0.066 seconds
[2024-03-09T01:30:00.683+0000] {processor.py:161} INFO - Started process (PID=214) to work on /opt/airflow/dags/dag1.py
[2024-03-09T01:30:00.686+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag1.py for tasks to queue
[2024-03-09T01:30:00.689+0000] {logging_mixin.py:188} INFO - [2024-03-09T01:30:00.688+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/dag1.py
[2024-03-09T01:30:00.744+0000] {logging_mixin.py:188} INFO - [2024-03-09T01:30:00.743+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/dag1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag1.py", line 4, in <module>
    from scrape_hocky import scrape_hockey_data, save_to_csv as save_hockey_to_csv
  File "/opt/airflow/dags/scrape_hocky.py", line 4, in <module>
    import pymongo
ModuleNotFoundError: No module named 'pymongo'
[2024-03-09T01:30:00.744+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag1.py
[2024-03-09T01:30:00.754+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag1.py took 0.074 seconds
[2024-03-09T01:30:53.471+0000] {processor.py:161} INFO - Started process (PID=44) to work on /opt/airflow/dags/dag1.py
[2024-03-09T01:30:53.472+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag1.py for tasks to queue
[2024-03-09T01:30:53.474+0000] {logging_mixin.py:188} INFO - [2024-03-09T01:30:53.473+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/dag1.py
[2024-03-09T01:30:53.552+0000] {logging_mixin.py:188} INFO - [2024-03-09T01:30:53.551+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/dag1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag1.py", line 4, in <module>
    from scrape_hocky import scrape_hockey_data, save_to_csv as save_hockey_to_csv
  File "/opt/airflow/dags/scrape_hocky.py", line 4, in <module>
    import pymongo
ModuleNotFoundError: No module named 'pymongo'
[2024-03-09T01:30:53.552+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag1.py
[2024-03-09T01:30:53.573+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag1.py took 0.105 seconds
[2024-03-09T01:31:24.040+0000] {processor.py:161} INFO - Started process (PID=101) to work on /opt/airflow/dags/dag1.py
[2024-03-09T01:31:24.045+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag1.py for tasks to queue
[2024-03-09T01:31:24.046+0000] {logging_mixin.py:188} INFO - [2024-03-09T01:31:24.046+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/dag1.py
[2024-03-09T01:31:24.090+0000] {logging_mixin.py:188} INFO - [2024-03-09T01:31:24.089+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/dag1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag1.py", line 4, in <module>
    from scrape_hocky import scrape_hockey_data, save_to_csv as save_hockey_to_csv
  File "/opt/airflow/dags/scrape_hocky.py", line 4, in <module>
    import pymongo
ModuleNotFoundError: No module named 'pymongo'
[2024-03-09T01:31:24.090+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag1.py
[2024-03-09T01:31:24.099+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag1.py took 0.061 seconds
[2024-03-09T01:31:54.163+0000] {processor.py:161} INFO - Started process (PID=158) to work on /opt/airflow/dags/dag1.py
[2024-03-09T01:31:54.166+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag1.py for tasks to queue
[2024-03-09T01:31:54.167+0000] {logging_mixin.py:188} INFO - [2024-03-09T01:31:54.167+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/dag1.py
[2024-03-09T01:31:54.206+0000] {logging_mixin.py:188} INFO - [2024-03-09T01:31:54.206+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/dag1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag1.py", line 4, in <module>
    from scrape_hocky import scrape_hockey_data, save_to_csv as save_hockey_to_csv
  File "/opt/airflow/dags/scrape_hocky.py", line 4, in <module>
    import pymongo
ModuleNotFoundError: No module named 'pymongo'
[2024-03-09T01:31:54.206+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag1.py
[2024-03-09T01:31:54.216+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag1.py took 0.056 seconds
[2024-03-09T01:32:24.697+0000] {processor.py:161} INFO - Started process (PID=215) to work on /opt/airflow/dags/dag1.py
[2024-03-09T01:32:24.701+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag1.py for tasks to queue
[2024-03-09T01:32:24.702+0000] {logging_mixin.py:188} INFO - [2024-03-09T01:32:24.702+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/dag1.py
[2024-03-09T01:32:24.748+0000] {logging_mixin.py:188} INFO - [2024-03-09T01:32:24.747+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/dag1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag1.py", line 4, in <module>
    from scrape_hocky import scrape_hockey_data, save_to_csv as save_hockey_to_csv
  File "/opt/airflow/dags/scrape_hocky.py", line 4, in <module>
    import pymongo
ModuleNotFoundError: No module named 'pymongo'
[2024-03-09T01:32:24.748+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag1.py
[2024-03-09T01:32:24.760+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag1.py took 0.065 seconds
[2024-03-09T01:32:55.201+0000] {processor.py:161} INFO - Started process (PID=272) to work on /opt/airflow/dags/dag1.py
[2024-03-09T01:32:55.202+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag1.py for tasks to queue
[2024-03-09T01:32:55.204+0000] {logging_mixin.py:188} INFO - [2024-03-09T01:32:55.203+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/dag1.py
[2024-03-09T01:32:55.249+0000] {logging_mixin.py:188} INFO - [2024-03-09T01:32:55.249+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/dag1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag1.py", line 4, in <module>
    from scrape_hocky import scrape_hockey_data, save_to_csv as save_hockey_to_csv
  File "/opt/airflow/dags/scrape_hocky.py", line 4, in <module>
    import pymongo
ModuleNotFoundError: No module named 'pymongo'
[2024-03-09T01:32:55.249+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag1.py
[2024-03-09T01:32:55.258+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag1.py took 0.060 seconds
[2024-03-09T01:33:25.768+0000] {processor.py:161} INFO - Started process (PID=329) to work on /opt/airflow/dags/dag1.py
[2024-03-09T01:33:25.769+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag1.py for tasks to queue
[2024-03-09T01:33:25.769+0000] {logging_mixin.py:188} INFO - [2024-03-09T01:33:25.769+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/dag1.py
[2024-03-09T01:33:25.812+0000] {logging_mixin.py:188} INFO - [2024-03-09T01:33:25.811+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/dag1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag1.py", line 4, in <module>
    from scrape_hocky import scrape_hockey_data, save_to_csv as save_hockey_to_csv
  File "/opt/airflow/dags/scrape_hocky.py", line 4, in <module>
    import pymongo
ModuleNotFoundError: No module named 'pymongo'
[2024-03-09T01:33:25.812+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag1.py
[2024-03-09T01:33:25.821+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag1.py took 0.054 seconds
[2024-03-09T01:33:56.258+0000] {processor.py:161} INFO - Started process (PID=386) to work on /opt/airflow/dags/dag1.py
[2024-03-09T01:33:56.261+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag1.py for tasks to queue
[2024-03-09T01:33:56.262+0000] {logging_mixin.py:188} INFO - [2024-03-09T01:33:56.262+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/dag1.py
[2024-03-09T01:33:56.307+0000] {logging_mixin.py:188} INFO - [2024-03-09T01:33:56.306+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/dag1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag1.py", line 4, in <module>
    from scrape_hocky import scrape_hockey_data, save_to_csv as save_hockey_to_csv
  File "/opt/airflow/dags/scrape_hocky.py", line 4, in <module>
    import pymongo
ModuleNotFoundError: No module named 'pymongo'
[2024-03-09T01:33:56.307+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag1.py
[2024-03-09T01:33:56.317+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag1.py took 0.062 seconds
[2024-03-09T01:34:27.140+0000] {processor.py:161} INFO - Started process (PID=443) to work on /opt/airflow/dags/dag1.py
[2024-03-09T01:34:27.141+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag1.py for tasks to queue
[2024-03-09T01:34:27.144+0000] {logging_mixin.py:188} INFO - [2024-03-09T01:34:27.143+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/dag1.py
[2024-03-09T01:34:27.190+0000] {logging_mixin.py:188} INFO - [2024-03-09T01:34:27.190+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/dag1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag1.py", line 4, in <module>
    from scrape_hocky import scrape_hockey_data, save_to_csv as save_hockey_to_csv
  File "/opt/airflow/dags/scrape_hocky.py", line 4, in <module>
    import pymongo
ModuleNotFoundError: No module named 'pymongo'
[2024-03-09T01:34:27.191+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag1.py
[2024-03-09T01:34:27.201+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag1.py took 0.065 seconds
[2024-03-09T01:34:57.288+0000] {processor.py:161} INFO - Started process (PID=500) to work on /opt/airflow/dags/dag1.py
[2024-03-09T01:34:57.292+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag1.py for tasks to queue
[2024-03-09T01:34:57.294+0000] {logging_mixin.py:188} INFO - [2024-03-09T01:34:57.294+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/dag1.py
[2024-03-09T01:34:57.336+0000] {logging_mixin.py:188} INFO - [2024-03-09T01:34:57.336+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/dag1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag1.py", line 4, in <module>
    from scrape_hocky import scrape_hockey_data, save_to_csv as save_hockey_to_csv
  File "/opt/airflow/dags/scrape_hocky.py", line 4, in <module>
    import pymongo
ModuleNotFoundError: No module named 'pymongo'
[2024-03-09T01:34:57.336+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag1.py
[2024-03-09T01:34:57.347+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag1.py took 0.060 seconds
[2024-03-09T01:35:28.124+0000] {processor.py:161} INFO - Started process (PID=557) to work on /opt/airflow/dags/dag1.py
[2024-03-09T01:35:28.124+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag1.py for tasks to queue
[2024-03-09T01:35:28.125+0000] {logging_mixin.py:188} INFO - [2024-03-09T01:35:28.125+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/dag1.py
[2024-03-09T01:35:28.164+0000] {logging_mixin.py:188} INFO - [2024-03-09T01:35:28.164+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/dag1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag1.py", line 4, in <module>
    from scrape_hocky import scrape_hockey_data, save_to_csv as save_hockey_to_csv
  File "/opt/airflow/dags/scrape_hocky.py", line 4, in <module>
    import pymongo
ModuleNotFoundError: No module named 'pymongo'
[2024-03-09T01:35:28.164+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag1.py
[2024-03-09T01:35:28.174+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag1.py took 0.051 seconds
[2024-03-09T01:35:58.702+0000] {processor.py:161} INFO - Started process (PID=614) to work on /opt/airflow/dags/dag1.py
[2024-03-09T01:35:58.706+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag1.py for tasks to queue
[2024-03-09T01:35:58.707+0000] {logging_mixin.py:188} INFO - [2024-03-09T01:35:58.707+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/dag1.py
[2024-03-09T01:35:58.751+0000] {logging_mixin.py:188} INFO - [2024-03-09T01:35:58.751+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/dag1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag1.py", line 4, in <module>
    from scrape_hocky import scrape_hockey_data, save_to_csv as save_hockey_to_csv
  File "/opt/airflow/dags/scrape_hocky.py", line 4, in <module>
    import pymongo
ModuleNotFoundError: No module named 'pymongo'
[2024-03-09T01:35:58.752+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag1.py
[2024-03-09T01:35:58.760+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag1.py took 0.060 seconds
[2024-03-09T01:36:29.187+0000] {processor.py:161} INFO - Started process (PID=671) to work on /opt/airflow/dags/dag1.py
[2024-03-09T01:36:29.188+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag1.py for tasks to queue
[2024-03-09T01:36:29.189+0000] {logging_mixin.py:188} INFO - [2024-03-09T01:36:29.189+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/dag1.py
[2024-03-09T01:36:29.232+0000] {logging_mixin.py:188} INFO - [2024-03-09T01:36:29.231+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/dag1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag1.py", line 4, in <module>
    from scrape_hocky import scrape_hockey_data, save_to_csv as save_hockey_to_csv
  File "/opt/airflow/dags/scrape_hocky.py", line 4, in <module>
    import pymongo
ModuleNotFoundError: No module named 'pymongo'
[2024-03-09T01:36:29.232+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag1.py
[2024-03-09T01:36:29.242+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag1.py took 0.061 seconds
[2024-03-09T01:36:59.863+0000] {processor.py:161} INFO - Started process (PID=728) to work on /opt/airflow/dags/dag1.py
[2024-03-09T01:36:59.865+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag1.py for tasks to queue
[2024-03-09T01:36:59.867+0000] {logging_mixin.py:188} INFO - [2024-03-09T01:36:59.867+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/dag1.py
[2024-03-09T01:36:59.915+0000] {logging_mixin.py:188} INFO - [2024-03-09T01:36:59.914+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/dag1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag1.py", line 4, in <module>
    from scrape_hocky import scrape_hockey_data, save_to_csv as save_hockey_to_csv
  File "/opt/airflow/dags/scrape_hocky.py", line 4, in <module>
    import pymongo
ModuleNotFoundError: No module named 'pymongo'
[2024-03-09T01:36:59.915+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag1.py
[2024-03-09T01:36:59.926+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag1.py took 0.067 seconds
[2024-03-09T01:37:30.504+0000] {processor.py:161} INFO - Started process (PID=785) to work on /opt/airflow/dags/dag1.py
[2024-03-09T01:37:30.505+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag1.py for tasks to queue
[2024-03-09T01:37:30.507+0000] {logging_mixin.py:188} INFO - [2024-03-09T01:37:30.507+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/dag1.py
[2024-03-09T01:37:30.549+0000] {logging_mixin.py:188} INFO - [2024-03-09T01:37:30.549+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/dag1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag1.py", line 4, in <module>
    from scrape_hocky import scrape_hockey_data, save_to_csv as save_hockey_to_csv
  File "/opt/airflow/dags/scrape_hocky.py", line 4, in <module>
    import pymongo
ModuleNotFoundError: No module named 'pymongo'
[2024-03-09T01:37:30.550+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag1.py
[2024-03-09T01:37:30.558+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag1.py took 0.060 seconds
[2024-03-09T01:38:01.157+0000] {processor.py:161} INFO - Started process (PID=842) to work on /opt/airflow/dags/dag1.py
[2024-03-09T01:38:01.158+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag1.py for tasks to queue
[2024-03-09T01:38:01.160+0000] {logging_mixin.py:188} INFO - [2024-03-09T01:38:01.160+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/dag1.py
[2024-03-09T01:38:01.205+0000] {logging_mixin.py:188} INFO - [2024-03-09T01:38:01.204+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/dag1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag1.py", line 4, in <module>
    from scrape_hocky import scrape_hockey_data, save_to_csv as save_hockey_to_csv
  File "/opt/airflow/dags/scrape_hocky.py", line 4, in <module>
    import pymongo
ModuleNotFoundError: No module named 'pymongo'
[2024-03-09T01:38:01.205+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag1.py
[2024-03-09T01:38:01.218+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag1.py took 0.065 seconds
[2024-03-09T01:38:31.675+0000] {processor.py:161} INFO - Started process (PID=899) to work on /opt/airflow/dags/dag1.py
[2024-03-09T01:38:31.677+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag1.py for tasks to queue
[2024-03-09T01:38:31.680+0000] {logging_mixin.py:188} INFO - [2024-03-09T01:38:31.679+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/dag1.py
[2024-03-09T01:38:31.729+0000] {logging_mixin.py:188} INFO - [2024-03-09T01:38:31.728+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/dag1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag1.py", line 4, in <module>
    from scrape_hocky import scrape_hockey_data, save_to_csv as save_hockey_to_csv
  File "/opt/airflow/dags/scrape_hocky.py", line 4, in <module>
    import pymongo
ModuleNotFoundError: No module named 'pymongo'
[2024-03-09T01:38:31.729+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag1.py
[2024-03-09T01:38:31.739+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag1.py took 0.068 seconds
[2024-03-09T01:39:02.147+0000] {processor.py:161} INFO - Started process (PID=956) to work on /opt/airflow/dags/dag1.py
[2024-03-09T01:39:02.152+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag1.py for tasks to queue
[2024-03-09T01:39:02.154+0000] {logging_mixin.py:188} INFO - [2024-03-09T01:39:02.154+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/dag1.py
[2024-03-09T01:39:02.199+0000] {logging_mixin.py:188} INFO - [2024-03-09T01:39:02.198+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/dag1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag1.py", line 4, in <module>
    from scrape_hocky import scrape_hockey_data, save_to_csv as save_hockey_to_csv
  File "/opt/airflow/dags/scrape_hocky.py", line 4, in <module>
    import pymongo
ModuleNotFoundError: No module named 'pymongo'
[2024-03-09T01:39:02.199+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag1.py
[2024-03-09T01:39:02.208+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag1.py took 0.064 seconds
[2024-03-09T01:39:32.665+0000] {processor.py:161} INFO - Started process (PID=1013) to work on /opt/airflow/dags/dag1.py
[2024-03-09T01:39:32.667+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag1.py for tasks to queue
[2024-03-09T01:39:32.669+0000] {logging_mixin.py:188} INFO - [2024-03-09T01:39:32.669+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/dag1.py
[2024-03-09T01:39:32.717+0000] {logging_mixin.py:188} INFO - [2024-03-09T01:39:32.716+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/dag1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag1.py", line 4, in <module>
    from scrape_hocky import scrape_hockey_data, save_to_csv as save_hockey_to_csv
  File "/opt/airflow/dags/scrape_hocky.py", line 4, in <module>
    import pymongo
ModuleNotFoundError: No module named 'pymongo'
[2024-03-09T01:39:32.717+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag1.py
[2024-03-09T01:39:32.729+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag1.py took 0.068 seconds
[2024-03-09T01:40:03.150+0000] {processor.py:161} INFO - Started process (PID=1070) to work on /opt/airflow/dags/dag1.py
[2024-03-09T01:40:03.150+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag1.py for tasks to queue
[2024-03-09T01:40:03.151+0000] {logging_mixin.py:188} INFO - [2024-03-09T01:40:03.151+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/dag1.py
[2024-03-09T01:40:03.197+0000] {logging_mixin.py:188} INFO - [2024-03-09T01:40:03.197+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/dag1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag1.py", line 4, in <module>
    from scrape_hocky import scrape_hockey_data, save_to_csv as save_hockey_to_csv
  File "/opt/airflow/dags/scrape_hocky.py", line 4, in <module>
    import pymongo
ModuleNotFoundError: No module named 'pymongo'
[2024-03-09T01:40:03.198+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag1.py
[2024-03-09T01:40:03.214+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag1.py took 0.066 seconds
[2024-03-09T01:40:33.782+0000] {processor.py:161} INFO - Started process (PID=1127) to work on /opt/airflow/dags/dag1.py
[2024-03-09T01:40:33.786+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag1.py for tasks to queue
[2024-03-09T01:40:33.788+0000] {logging_mixin.py:188} INFO - [2024-03-09T01:40:33.788+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/dag1.py
[2024-03-09T01:40:33.833+0000] {logging_mixin.py:188} INFO - [2024-03-09T01:40:33.833+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/dag1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag1.py", line 4, in <module>
    from scrape_hocky import scrape_hockey_data, save_to_csv as save_hockey_to_csv
  File "/opt/airflow/dags/scrape_hocky.py", line 4, in <module>
    import pymongo
ModuleNotFoundError: No module named 'pymongo'
[2024-03-09T01:40:33.833+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag1.py
[2024-03-09T01:40:33.843+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag1.py took 0.064 seconds
[2024-03-09T01:41:04.546+0000] {processor.py:161} INFO - Started process (PID=1184) to work on /opt/airflow/dags/dag1.py
[2024-03-09T01:41:04.549+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag1.py for tasks to queue
[2024-03-09T01:41:04.551+0000] {logging_mixin.py:188} INFO - [2024-03-09T01:41:04.551+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/dag1.py
[2024-03-09T01:41:04.599+0000] {logging_mixin.py:188} INFO - [2024-03-09T01:41:04.598+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/dag1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag1.py", line 4, in <module>
    from scrape_hocky import scrape_hockey_data, save_to_csv as save_hockey_to_csv
  File "/opt/airflow/dags/scrape_hocky.py", line 4, in <module>
    import pymongo
ModuleNotFoundError: No module named 'pymongo'
[2024-03-09T01:41:04.599+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag1.py
[2024-03-09T01:41:04.613+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag1.py took 0.071 seconds
[2024-03-09T01:41:35.060+0000] {processor.py:161} INFO - Started process (PID=1240) to work on /opt/airflow/dags/dag1.py
[2024-03-09T01:41:35.062+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag1.py for tasks to queue
[2024-03-09T01:41:35.063+0000] {logging_mixin.py:188} INFO - [2024-03-09T01:41:35.063+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/dag1.py
[2024-03-09T01:41:35.106+0000] {logging_mixin.py:188} INFO - [2024-03-09T01:41:35.105+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/dag1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag1.py", line 4, in <module>
    from scrape_hocky import scrape_hockey_data, save_to_csv as save_hockey_to_csv
  File "/opt/airflow/dags/scrape_hocky.py", line 4, in <module>
    import pymongo
ModuleNotFoundError: No module named 'pymongo'
[2024-03-09T01:41:35.106+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag1.py
[2024-03-09T01:41:35.116+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag1.py took 0.059 seconds
[2024-03-09T01:42:05.600+0000] {processor.py:161} INFO - Started process (PID=1297) to work on /opt/airflow/dags/dag1.py
[2024-03-09T01:42:05.603+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag1.py for tasks to queue
[2024-03-09T01:42:05.605+0000] {logging_mixin.py:188} INFO - [2024-03-09T01:42:05.605+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/dag1.py
[2024-03-09T01:42:05.649+0000] {logging_mixin.py:188} INFO - [2024-03-09T01:42:05.648+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/dag1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag1.py", line 4, in <module>
    from scrape_hocky import scrape_hockey_data, save_to_csv as save_hockey_to_csv
  File "/opt/airflow/dags/scrape_hocky.py", line 4, in <module>
    import pymongo
ModuleNotFoundError: No module named 'pymongo'
[2024-03-09T01:42:05.649+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag1.py
[2024-03-09T01:42:05.658+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag1.py took 0.061 seconds
[2024-03-09T01:42:36.068+0000] {processor.py:161} INFO - Started process (PID=1354) to work on /opt/airflow/dags/dag1.py
[2024-03-09T01:42:36.071+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag1.py for tasks to queue
[2024-03-09T01:42:36.073+0000] {logging_mixin.py:188} INFO - [2024-03-09T01:42:36.073+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/dag1.py
[2024-03-09T01:42:36.116+0000] {logging_mixin.py:188} INFO - [2024-03-09T01:42:36.116+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/dag1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag1.py", line 4, in <module>
    from scrape_hocky import scrape_hockey_data, save_to_csv as save_hockey_to_csv
  File "/opt/airflow/dags/scrape_hocky.py", line 4, in <module>
    import pymongo
ModuleNotFoundError: No module named 'pymongo'
[2024-03-09T01:42:36.116+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag1.py
[2024-03-09T01:42:36.125+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag1.py took 0.061 seconds
[2024-03-09T01:43:06.552+0000] {processor.py:161} INFO - Started process (PID=1411) to work on /opt/airflow/dags/dag1.py
[2024-03-09T01:43:06.554+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag1.py for tasks to queue
[2024-03-09T01:43:06.556+0000] {logging_mixin.py:188} INFO - [2024-03-09T01:43:06.555+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/dag1.py
[2024-03-09T01:43:06.602+0000] {logging_mixin.py:188} INFO - [2024-03-09T01:43:06.602+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/dag1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag1.py", line 4, in <module>
    from scrape_hocky import scrape_hockey_data, save_to_csv as save_hockey_to_csv
  File "/opt/airflow/dags/scrape_hocky.py", line 4, in <module>
    import pymongo
ModuleNotFoundError: No module named 'pymongo'
[2024-03-09T01:43:06.603+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag1.py
[2024-03-09T01:43:06.612+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag1.py took 0.063 seconds
[2024-03-09T01:43:37.156+0000] {processor.py:161} INFO - Started process (PID=1468) to work on /opt/airflow/dags/dag1.py
[2024-03-09T01:43:37.157+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag1.py for tasks to queue
[2024-03-09T01:43:37.158+0000] {logging_mixin.py:188} INFO - [2024-03-09T01:43:37.158+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/dag1.py
[2024-03-09T01:43:37.205+0000] {logging_mixin.py:188} INFO - [2024-03-09T01:43:37.205+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/dag1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag1.py", line 4, in <module>
    from scrape_hocky import scrape_hockey_data, save_to_csv as save_hockey_to_csv
  File "/opt/airflow/dags/scrape_hocky.py", line 4, in <module>
    import pymongo
ModuleNotFoundError: No module named 'pymongo'
[2024-03-09T01:43:37.205+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag1.py
[2024-03-09T01:43:37.214+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag1.py took 0.062 seconds
[2024-03-09T01:44:07.705+0000] {processor.py:161} INFO - Started process (PID=1525) to work on /opt/airflow/dags/dag1.py
[2024-03-09T01:44:07.707+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag1.py for tasks to queue
[2024-03-09T01:44:07.708+0000] {logging_mixin.py:188} INFO - [2024-03-09T01:44:07.708+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/dag1.py
[2024-03-09T01:44:07.758+0000] {logging_mixin.py:188} INFO - [2024-03-09T01:44:07.757+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/dag1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag1.py", line 4, in <module>
    from scrape_hocky import scrape_hockey_data, save_to_csv as save_hockey_to_csv
  File "/opt/airflow/dags/scrape_hocky.py", line 4, in <module>
    import pymongo
ModuleNotFoundError: No module named 'pymongo'
[2024-03-09T01:44:07.758+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag1.py
[2024-03-09T01:44:07.769+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag1.py took 0.068 seconds
[2024-03-09T01:44:38.404+0000] {processor.py:161} INFO - Started process (PID=1582) to work on /opt/airflow/dags/dag1.py
[2024-03-09T01:44:38.405+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag1.py for tasks to queue
[2024-03-09T01:44:38.407+0000] {logging_mixin.py:188} INFO - [2024-03-09T01:44:38.406+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/dag1.py
[2024-03-09T01:44:38.446+0000] {logging_mixin.py:188} INFO - [2024-03-09T01:44:38.445+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/dag1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag1.py", line 4, in <module>
    from scrape_hocky import scrape_hockey_data, save_to_csv as save_hockey_to_csv
  File "/opt/airflow/dags/scrape_hocky.py", line 4, in <module>
    import pymongo
ModuleNotFoundError: No module named 'pymongo'
[2024-03-09T01:44:38.446+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag1.py
[2024-03-09T01:44:38.455+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag1.py took 0.055 seconds
[2024-03-09T01:45:08.962+0000] {processor.py:161} INFO - Started process (PID=1639) to work on /opt/airflow/dags/dag1.py
[2024-03-09T01:45:08.963+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag1.py for tasks to queue
[2024-03-09T01:45:08.965+0000] {logging_mixin.py:188} INFO - [2024-03-09T01:45:08.965+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/dag1.py
[2024-03-09T01:45:09.010+0000] {logging_mixin.py:188} INFO - [2024-03-09T01:45:09.010+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/dag1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag1.py", line 4, in <module>
    from scrape_hocky import scrape_hockey_data, save_to_csv as save_hockey_to_csv
  File "/opt/airflow/dags/scrape_hocky.py", line 4, in <module>
    import pymongo
ModuleNotFoundError: No module named 'pymongo'
[2024-03-09T01:45:09.011+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag1.py
[2024-03-09T01:45:09.022+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag1.py took 0.064 seconds
[2024-03-09T01:45:39.496+0000] {processor.py:161} INFO - Started process (PID=1696) to work on /opt/airflow/dags/dag1.py
[2024-03-09T01:45:39.497+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag1.py for tasks to queue
[2024-03-09T01:45:39.501+0000] {logging_mixin.py:188} INFO - [2024-03-09T01:45:39.500+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/dag1.py
[2024-03-09T01:45:39.547+0000] {logging_mixin.py:188} INFO - [2024-03-09T01:45:39.546+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/dag1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag1.py", line 4, in <module>
    from scrape_hocky import scrape_hockey_data, save_to_csv as save_hockey_to_csv
  File "/opt/airflow/dags/scrape_hocky.py", line 4, in <module>
    import pymongo
ModuleNotFoundError: No module named 'pymongo'
[2024-03-09T01:45:39.547+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag1.py
[2024-03-09T01:45:39.557+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag1.py took 0.065 seconds
[2024-03-09T01:47:49.768+0000] {processor.py:161} INFO - Started process (PID=43) to work on /opt/airflow/dags/dag1.py
[2024-03-09T01:47:49.768+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag1.py for tasks to queue
[2024-03-09T01:47:49.769+0000] {logging_mixin.py:188} INFO - [2024-03-09T01:47:49.769+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/dag1.py
[2024-03-09T01:47:49.845+0000] {logging_mixin.py:188} INFO - [2024-03-09T01:47:49.844+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/dag1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag1.py", line 4, in <module>
    from scrape_hocky import scrape_hockey_data, save_to_csv as save_hockey_to_csv
  File "/opt/airflow/dags/scrape_hocky.py", line 4, in <module>
    import pymongo
ModuleNotFoundError: No module named 'pymongo'
[2024-03-09T01:47:49.845+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag1.py
[2024-03-09T01:47:49.856+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag1.py took 0.090 seconds
[2024-03-09T01:48:20.300+0000] {processor.py:161} INFO - Started process (PID=100) to work on /opt/airflow/dags/dag1.py
[2024-03-09T01:48:20.300+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag1.py for tasks to queue
[2024-03-09T01:48:20.301+0000] {logging_mixin.py:188} INFO - [2024-03-09T01:48:20.301+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/dag1.py
[2024-03-09T01:48:20.347+0000] {logging_mixin.py:188} INFO - [2024-03-09T01:48:20.346+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/dag1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag1.py", line 4, in <module>
    from scrape_hocky import scrape_hockey_data, save_to_csv as save_hockey_to_csv
  File "/opt/airflow/dags/scrape_hocky.py", line 4, in <module>
    import pymongo
ModuleNotFoundError: No module named 'pymongo'
[2024-03-09T01:48:20.348+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag1.py
[2024-03-09T01:48:20.362+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag1.py took 0.064 seconds
[2024-03-09T01:48:51.058+0000] {processor.py:161} INFO - Started process (PID=157) to work on /opt/airflow/dags/dag1.py
[2024-03-09T01:48:51.059+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag1.py for tasks to queue
[2024-03-09T01:48:51.060+0000] {logging_mixin.py:188} INFO - [2024-03-09T01:48:51.060+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/dag1.py
[2024-03-09T01:48:51.103+0000] {logging_mixin.py:188} INFO - [2024-03-09T01:48:51.103+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/dag1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag1.py", line 4, in <module>
    from scrape_hocky import scrape_hockey_data, save_to_csv as save_hockey_to_csv
  File "/opt/airflow/dags/scrape_hocky.py", line 4, in <module>
    import pymongo
ModuleNotFoundError: No module named 'pymongo'
[2024-03-09T01:48:51.103+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag1.py
[2024-03-09T01:48:51.115+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag1.py took 0.062 seconds
[2024-03-09T01:49:21.803+0000] {processor.py:161} INFO - Started process (PID=214) to work on /opt/airflow/dags/dag1.py
[2024-03-09T01:49:21.804+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag1.py for tasks to queue
[2024-03-09T01:49:21.805+0000] {logging_mixin.py:188} INFO - [2024-03-09T01:49:21.805+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/dag1.py
[2024-03-09T01:49:21.846+0000] {logging_mixin.py:188} INFO - [2024-03-09T01:49:21.846+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/dag1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag1.py", line 4, in <module>
    from scrape_hocky import scrape_hockey_data, save_to_csv as save_hockey_to_csv
  File "/opt/airflow/dags/scrape_hocky.py", line 4, in <module>
    import pymongo
ModuleNotFoundError: No module named 'pymongo'
[2024-03-09T01:49:21.847+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag1.py
[2024-03-09T01:49:21.857+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag1.py took 0.057 seconds
[2024-03-09T01:49:52.415+0000] {processor.py:161} INFO - Started process (PID=271) to work on /opt/airflow/dags/dag1.py
[2024-03-09T01:49:52.416+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag1.py for tasks to queue
[2024-03-09T01:49:52.418+0000] {logging_mixin.py:188} INFO - [2024-03-09T01:49:52.418+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/dag1.py
[2024-03-09T01:49:52.462+0000] {logging_mixin.py:188} INFO - [2024-03-09T01:49:52.461+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/dag1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag1.py", line 4, in <module>
    from scrape_hocky import scrape_hockey_data, save_to_csv as save_hockey_to_csv
  File "/opt/airflow/dags/scrape_hocky.py", line 4, in <module>
    import pymongo
ModuleNotFoundError: No module named 'pymongo'
[2024-03-09T01:49:52.462+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag1.py
[2024-03-09T01:49:52.473+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag1.py took 0.061 seconds
[2024-03-09T01:50:22.988+0000] {processor.py:161} INFO - Started process (PID=328) to work on /opt/airflow/dags/dag1.py
[2024-03-09T01:50:22.989+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag1.py for tasks to queue
[2024-03-09T01:50:22.990+0000] {logging_mixin.py:188} INFO - [2024-03-09T01:50:22.990+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/dag1.py
[2024-03-09T01:50:23.037+0000] {logging_mixin.py:188} INFO - [2024-03-09T01:50:23.037+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/dag1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag1.py", line 4, in <module>
    from scrape_hocky import scrape_hockey_data, save_to_csv as save_hockey_to_csv
  File "/opt/airflow/dags/scrape_hocky.py", line 4, in <module>
    import pymongo
ModuleNotFoundError: No module named 'pymongo'
[2024-03-09T01:50:23.038+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag1.py
[2024-03-09T01:50:23.048+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag1.py took 0.062 seconds
[2024-03-09T01:50:53.628+0000] {processor.py:161} INFO - Started process (PID=385) to work on /opt/airflow/dags/dag1.py
[2024-03-09T01:50:53.632+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag1.py for tasks to queue
[2024-03-09T01:50:53.633+0000] {logging_mixin.py:188} INFO - [2024-03-09T01:50:53.633+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/dag1.py
[2024-03-09T01:50:53.679+0000] {logging_mixin.py:188} INFO - [2024-03-09T01:50:53.679+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/dag1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag1.py", line 4, in <module>
    from scrape_hocky import scrape_hockey_data, save_to_csv as save_hockey_to_csv
  File "/opt/airflow/dags/scrape_hocky.py", line 4, in <module>
    import pymongo
ModuleNotFoundError: No module named 'pymongo'
[2024-03-09T01:50:53.679+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag1.py
[2024-03-09T01:50:53.689+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag1.py took 0.063 seconds
[2024-03-09T01:51:24.130+0000] {processor.py:161} INFO - Started process (PID=442) to work on /opt/airflow/dags/dag1.py
[2024-03-09T01:51:24.135+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag1.py for tasks to queue
[2024-03-09T01:51:24.136+0000] {logging_mixin.py:188} INFO - [2024-03-09T01:51:24.136+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/dag1.py
[2024-03-09T01:51:24.186+0000] {logging_mixin.py:188} INFO - [2024-03-09T01:51:24.186+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/dag1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag1.py", line 4, in <module>
    from scrape_hocky import scrape_hockey_data, save_to_csv as save_hockey_to_csv
  File "/opt/airflow/dags/scrape_hocky.py", line 4, in <module>
    import pymongo
ModuleNotFoundError: No module named 'pymongo'
[2024-03-09T01:51:24.187+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag1.py
[2024-03-09T01:51:24.195+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag1.py took 0.067 seconds
[2024-03-09T01:51:54.706+0000] {processor.py:161} INFO - Started process (PID=499) to work on /opt/airflow/dags/dag1.py
[2024-03-09T01:51:54.709+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag1.py for tasks to queue
[2024-03-09T01:51:54.710+0000] {logging_mixin.py:188} INFO - [2024-03-09T01:51:54.710+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/dag1.py
[2024-03-09T01:51:54.753+0000] {logging_mixin.py:188} INFO - [2024-03-09T01:51:54.753+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/dag1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag1.py", line 4, in <module>
    from scrape_hocky import scrape_hockey_data, save_to_csv as save_hockey_to_csv
  File "/opt/airflow/dags/scrape_hocky.py", line 4, in <module>
    import pymongo
ModuleNotFoundError: No module named 'pymongo'
[2024-03-09T01:51:54.753+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag1.py
[2024-03-09T01:51:54.763+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag1.py took 0.060 seconds
[2024-03-09T01:52:25.151+0000] {processor.py:161} INFO - Started process (PID=556) to work on /opt/airflow/dags/dag1.py
[2024-03-09T01:52:25.156+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag1.py for tasks to queue
[2024-03-09T01:52:25.157+0000] {logging_mixin.py:188} INFO - [2024-03-09T01:52:25.156+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/dag1.py
[2024-03-09T01:52:25.200+0000] {logging_mixin.py:188} INFO - [2024-03-09T01:52:25.200+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/dag1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag1.py", line 4, in <module>
    from scrape_hocky import scrape_hockey_data, save_to_csv as save_hockey_to_csv
  File "/opt/airflow/dags/scrape_hocky.py", line 4, in <module>
    import pymongo
ModuleNotFoundError: No module named 'pymongo'
[2024-03-09T01:52:25.200+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag1.py
[2024-03-09T01:52:25.210+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag1.py took 0.061 seconds
[2024-03-09T01:52:55.678+0000] {processor.py:161} INFO - Started process (PID=613) to work on /opt/airflow/dags/dag1.py
[2024-03-09T01:52:55.678+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag1.py for tasks to queue
[2024-03-09T01:52:55.679+0000] {logging_mixin.py:188} INFO - [2024-03-09T01:52:55.679+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/dag1.py
[2024-03-09T01:52:55.719+0000] {logging_mixin.py:188} INFO - [2024-03-09T01:52:55.719+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/dag1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag1.py", line 4, in <module>
    from scrape_hocky import scrape_hockey_data, save_to_csv as save_hockey_to_csv
  File "/opt/airflow/dags/scrape_hocky.py", line 4, in <module>
    import pymongo
ModuleNotFoundError: No module named 'pymongo'
[2024-03-09T01:52:55.720+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag1.py
[2024-03-09T01:52:55.729+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag1.py took 0.053 seconds
[2024-03-09T01:53:31.059+0000] {processor.py:161} INFO - Started process (PID=43) to work on /opt/airflow/dags/dag1.py
[2024-03-09T01:53:31.060+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag1.py for tasks to queue
[2024-03-09T01:53:31.062+0000] {logging_mixin.py:188} INFO - [2024-03-09T01:53:31.061+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/dag1.py
[2024-03-09T01:53:31.141+0000] {logging_mixin.py:188} INFO - [2024-03-09T01:53:31.140+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/dag1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag1.py", line 4, in <module>
    from scrape_hocky import scrape_hockey_data, save_to_csv as save_hockey_to_csv
  File "/opt/airflow/dags/scrape_hocky.py", line 4, in <module>
    import pymongo
ModuleNotFoundError: No module named 'pymongo'
[2024-03-09T01:53:31.141+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag1.py
[2024-03-09T01:53:31.157+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag1.py took 0.100 seconds
[2024-03-09T01:54:01.726+0000] {processor.py:161} INFO - Started process (PID=100) to work on /opt/airflow/dags/dag1.py
[2024-03-09T01:54:01.731+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag1.py for tasks to queue
[2024-03-09T01:54:01.732+0000] {logging_mixin.py:188} INFO - [2024-03-09T01:54:01.732+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/dag1.py
[2024-03-09T01:54:01.775+0000] {logging_mixin.py:188} INFO - [2024-03-09T01:54:01.775+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/dag1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag1.py", line 4, in <module>
    from scrape_hocky import scrape_hockey_data, save_to_csv as save_hockey_to_csv
  File "/opt/airflow/dags/scrape_hocky.py", line 4, in <module>
    import pymongo
ModuleNotFoundError: No module named 'pymongo'
[2024-03-09T01:54:01.775+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag1.py
[2024-03-09T01:54:01.785+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag1.py took 0.062 seconds
[2024-03-09T01:54:32.012+0000] {processor.py:161} INFO - Started process (PID=157) to work on /opt/airflow/dags/dag1.py
[2024-03-09T01:54:32.014+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag1.py for tasks to queue
[2024-03-09T01:54:32.015+0000] {logging_mixin.py:188} INFO - [2024-03-09T01:54:32.015+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/dag1.py
[2024-03-09T01:54:32.056+0000] {logging_mixin.py:188} INFO - [2024-03-09T01:54:32.055+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/dag1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag1.py", line 4, in <module>
    from scrape_hocky import scrape_hockey_data, save_to_csv as save_hockey_to_csv
  File "/opt/airflow/dags/scrape_hocky.py", line 4, in <module>
    import pymongo
ModuleNotFoundError: No module named 'pymongo'
[2024-03-09T01:54:32.056+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag1.py
[2024-03-09T01:54:32.067+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag1.py took 0.058 seconds
[2024-03-09T01:55:02.742+0000] {processor.py:161} INFO - Started process (PID=214) to work on /opt/airflow/dags/dag1.py
[2024-03-09T01:55:02.743+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag1.py for tasks to queue
[2024-03-09T01:55:02.744+0000] {logging_mixin.py:188} INFO - [2024-03-09T01:55:02.744+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/dag1.py
[2024-03-09T01:55:02.783+0000] {logging_mixin.py:188} INFO - [2024-03-09T01:55:02.782+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/dag1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag1.py", line 4, in <module>
    from scrape_hocky import scrape_hockey_data, save_to_csv as save_hockey_to_csv
  File "/opt/airflow/dags/scrape_hocky.py", line 4, in <module>
    import pymongo
ModuleNotFoundError: No module named 'pymongo'
[2024-03-09T01:55:02.783+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag1.py
[2024-03-09T01:55:02.794+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag1.py took 0.055 seconds
[2024-03-09T01:55:33.262+0000] {processor.py:161} INFO - Started process (PID=271) to work on /opt/airflow/dags/dag1.py
[2024-03-09T01:55:33.262+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag1.py for tasks to queue
[2024-03-09T01:55:33.263+0000] {logging_mixin.py:188} INFO - [2024-03-09T01:55:33.263+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/dag1.py
[2024-03-09T01:55:33.306+0000] {logging_mixin.py:188} INFO - [2024-03-09T01:55:33.306+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/dag1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag1.py", line 4, in <module>
    from scrape_hocky import scrape_hockey_data, save_to_csv as save_hockey_to_csv
  File "/opt/airflow/dags/scrape_hocky.py", line 4, in <module>
    import pymongo
ModuleNotFoundError: No module named 'pymongo'
[2024-03-09T01:55:33.306+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag1.py
[2024-03-09T01:55:33.316+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag1.py took 0.057 seconds
[2024-03-09T01:56:03.732+0000] {processor.py:161} INFO - Started process (PID=328) to work on /opt/airflow/dags/dag1.py
[2024-03-09T01:56:03.732+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag1.py for tasks to queue
[2024-03-09T01:56:03.733+0000] {logging_mixin.py:188} INFO - [2024-03-09T01:56:03.733+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/dag1.py
[2024-03-09T01:56:03.772+0000] {logging_mixin.py:188} INFO - [2024-03-09T01:56:03.772+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/dag1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag1.py", line 4, in <module>
    from scrape_hocky import scrape_hockey_data, save_to_csv as save_hockey_to_csv
  File "/opt/airflow/dags/scrape_hocky.py", line 4, in <module>
    import pymongo
ModuleNotFoundError: No module named 'pymongo'
[2024-03-09T01:56:03.773+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag1.py
[2024-03-09T01:56:03.781+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag1.py took 0.052 seconds
[2024-03-09T01:56:34.227+0000] {processor.py:161} INFO - Started process (PID=385) to work on /opt/airflow/dags/dag1.py
[2024-03-09T01:56:34.230+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag1.py for tasks to queue
[2024-03-09T01:56:34.231+0000] {logging_mixin.py:188} INFO - [2024-03-09T01:56:34.230+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/dag1.py
[2024-03-09T01:56:34.272+0000] {logging_mixin.py:188} INFO - [2024-03-09T01:56:34.272+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/dag1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag1.py", line 4, in <module>
    from scrape_hocky import scrape_hockey_data, save_to_csv as save_hockey_to_csv
  File "/opt/airflow/dags/scrape_hocky.py", line 4, in <module>
    import pymongo
ModuleNotFoundError: No module named 'pymongo'
[2024-03-09T01:56:34.273+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag1.py
[2024-03-09T01:56:34.282+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag1.py took 0.058 seconds
[2024-03-09T01:57:04.710+0000] {processor.py:161} INFO - Started process (PID=442) to work on /opt/airflow/dags/dag1.py
[2024-03-09T01:57:04.715+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag1.py for tasks to queue
[2024-03-09T01:57:04.716+0000] {logging_mixin.py:188} INFO - [2024-03-09T01:57:04.716+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/dag1.py
[2024-03-09T01:57:04.762+0000] {logging_mixin.py:188} INFO - [2024-03-09T01:57:04.761+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/dag1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag1.py", line 4, in <module>
    from scrape_hocky import scrape_hockey_data, save_to_csv as save_hockey_to_csv
  File "/opt/airflow/dags/scrape_hocky.py", line 4, in <module>
    import pymongo
ModuleNotFoundError: No module named 'pymongo'
[2024-03-09T01:57:04.762+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag1.py
[2024-03-09T01:57:04.772+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag1.py took 0.065 seconds
[2024-03-09T01:57:35.384+0000] {processor.py:161} INFO - Started process (PID=499) to work on /opt/airflow/dags/dag1.py
[2024-03-09T01:57:35.386+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag1.py for tasks to queue
[2024-03-09T01:57:35.387+0000] {logging_mixin.py:188} INFO - [2024-03-09T01:57:35.387+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/dag1.py
[2024-03-09T01:57:35.438+0000] {logging_mixin.py:188} INFO - [2024-03-09T01:57:35.437+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/dag1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag1.py", line 4, in <module>
    from scrape_hocky import scrape_hockey_data, save_to_csv as save_hockey_to_csv
  File "/opt/airflow/dags/scrape_hocky.py", line 4, in <module>
    import pymongo
ModuleNotFoundError: No module named 'pymongo'
[2024-03-09T01:57:35.438+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag1.py
[2024-03-09T01:57:35.447+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag1.py took 0.067 seconds
[2024-03-09T01:58:05.967+0000] {processor.py:161} INFO - Started process (PID=556) to work on /opt/airflow/dags/dag1.py
[2024-03-09T01:58:05.972+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag1.py for tasks to queue
[2024-03-09T01:58:05.973+0000] {logging_mixin.py:188} INFO - [2024-03-09T01:58:05.973+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/dag1.py
[2024-03-09T01:58:06.015+0000] {logging_mixin.py:188} INFO - [2024-03-09T01:58:06.015+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/dag1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag1.py", line 4, in <module>
    from scrape_hocky import scrape_hockey_data, save_to_csv as save_hockey_to_csv
  File "/opt/airflow/dags/scrape_hocky.py", line 4, in <module>
    import pymongo
ModuleNotFoundError: No module named 'pymongo'
[2024-03-09T01:58:06.016+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag1.py
[2024-03-09T01:58:06.027+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag1.py took 0.062 seconds
[2024-03-09T01:58:36.551+0000] {processor.py:161} INFO - Started process (PID=613) to work on /opt/airflow/dags/dag1.py
[2024-03-09T01:58:36.556+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag1.py for tasks to queue
[2024-03-09T01:58:36.557+0000] {logging_mixin.py:188} INFO - [2024-03-09T01:58:36.556+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/dag1.py
[2024-03-09T01:58:36.597+0000] {logging_mixin.py:188} INFO - [2024-03-09T01:58:36.597+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/dag1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag1.py", line 4, in <module>
    from scrape_hocky import scrape_hockey_data, save_to_csv as save_hockey_to_csv
  File "/opt/airflow/dags/scrape_hocky.py", line 4, in <module>
    import pymongo
ModuleNotFoundError: No module named 'pymongo'
[2024-03-09T01:58:36.597+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag1.py
[2024-03-09T01:58:36.606+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag1.py took 0.056 seconds
[2024-03-09T01:59:28.272+0000] {processor.py:161} INFO - Started process (PID=43) to work on /opt/airflow/dags/dag1.py
[2024-03-09T01:59:28.273+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag1.py for tasks to queue
[2024-03-09T01:59:28.275+0000] {logging_mixin.py:188} INFO - [2024-03-09T01:59:28.275+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/dag1.py
[2024-03-09T01:59:28.372+0000] {logging_mixin.py:188} INFO - [2024-03-09T01:59:28.371+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/dag1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag1.py", line 4, in <module>
    from scrape_hocky import scrape_hockey_data, save_to_csv as save_hockey_to_csv
  File "/opt/airflow/dags/scrape_hocky.py", line 4, in <module>
    import pymongo
ModuleNotFoundError: No module named 'pymongo'
[2024-03-09T01:59:28.373+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag1.py
[2024-03-09T01:59:28.394+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag1.py took 0.125 seconds
[2024-03-09T01:59:58.683+0000] {processor.py:161} INFO - Started process (PID=100) to work on /opt/airflow/dags/dag1.py
[2024-03-09T01:59:58.684+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag1.py for tasks to queue
[2024-03-09T01:59:58.685+0000] {logging_mixin.py:188} INFO - [2024-03-09T01:59:58.685+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/dag1.py
[2024-03-09T01:59:58.731+0000] {logging_mixin.py:188} INFO - [2024-03-09T01:59:58.731+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/dag1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag1.py", line 4, in <module>
    from scrape_hocky import scrape_hockey_data, save_to_csv as save_hockey_to_csv
  File "/opt/airflow/dags/scrape_hocky.py", line 4, in <module>
    import pymongo
ModuleNotFoundError: No module named 'pymongo'
[2024-03-09T01:59:58.731+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag1.py
[2024-03-09T01:59:58.741+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag1.py took 0.062 seconds
[2024-03-09T02:00:29.261+0000] {processor.py:161} INFO - Started process (PID=157) to work on /opt/airflow/dags/dag1.py
[2024-03-09T02:00:29.262+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag1.py for tasks to queue
[2024-03-09T02:00:29.263+0000] {logging_mixin.py:188} INFO - [2024-03-09T02:00:29.263+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/dag1.py
[2024-03-09T02:00:29.305+0000] {logging_mixin.py:188} INFO - [2024-03-09T02:00:29.304+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/dag1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag1.py", line 4, in <module>
    from scrape_hocky import scrape_hockey_data, save_to_csv as save_hockey_to_csv
  File "/opt/airflow/dags/scrape_hocky.py", line 4, in <module>
    import pymongo
ModuleNotFoundError: No module named 'pymongo'
[2024-03-09T02:00:29.305+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag1.py
[2024-03-09T02:00:29.316+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag1.py took 0.058 seconds
[2024-03-09T02:00:59.797+0000] {processor.py:161} INFO - Started process (PID=214) to work on /opt/airflow/dags/dag1.py
[2024-03-09T02:00:59.803+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag1.py for tasks to queue
[2024-03-09T02:00:59.804+0000] {logging_mixin.py:188} INFO - [2024-03-09T02:00:59.804+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/dag1.py
[2024-03-09T02:00:59.849+0000] {logging_mixin.py:188} INFO - [2024-03-09T02:00:59.848+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/dag1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag1.py", line 4, in <module>
    from scrape_hocky import scrape_hockey_data, save_to_csv as save_hockey_to_csv
  File "/opt/airflow/dags/scrape_hocky.py", line 4, in <module>
    import pymongo
ModuleNotFoundError: No module named 'pymongo'
[2024-03-09T02:00:59.849+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag1.py
[2024-03-09T02:00:59.861+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag1.py took 0.066 seconds
[2024-03-09T02:01:30.541+0000] {processor.py:161} INFO - Started process (PID=271) to work on /opt/airflow/dags/dag1.py
[2024-03-09T02:01:30.544+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag1.py for tasks to queue
[2024-03-09T02:01:30.545+0000] {logging_mixin.py:188} INFO - [2024-03-09T02:01:30.545+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/dag1.py
[2024-03-09T02:01:30.592+0000] {logging_mixin.py:188} INFO - [2024-03-09T02:01:30.591+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/dag1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag1.py", line 4, in <module>
    from scrape_hocky import scrape_hockey_data, save_to_csv as save_hockey_to_csv
  File "/opt/airflow/dags/scrape_hocky.py", line 4, in <module>
    import pymongo
ModuleNotFoundError: No module named 'pymongo'
[2024-03-09T02:01:30.592+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag1.py
[2024-03-09T02:01:30.604+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag1.py took 0.066 seconds
[2024-03-09T02:02:01.094+0000] {processor.py:161} INFO - Started process (PID=328) to work on /opt/airflow/dags/dag1.py
[2024-03-09T02:02:01.097+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag1.py for tasks to queue
[2024-03-09T02:02:01.098+0000] {logging_mixin.py:188} INFO - [2024-03-09T02:02:01.098+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/dag1.py
[2024-03-09T02:02:01.136+0000] {logging_mixin.py:188} INFO - [2024-03-09T02:02:01.136+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/dag1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag1.py", line 4, in <module>
    from scrape_hocky import scrape_hockey_data, save_to_csv as save_hockey_to_csv
  File "/opt/airflow/dags/scrape_hocky.py", line 4, in <module>
    import pymongo
ModuleNotFoundError: No module named 'pymongo'
[2024-03-09T02:02:01.136+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag1.py
[2024-03-09T02:02:01.146+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag1.py took 0.055 seconds
